// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: grpc_service.proto

package pb

import (
	context "context"
	fmt "fmt"
	babuzapb "github.com/fanaujie/babuza/ibabuza/babuzapb"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

func init() { proto.RegisterFile("grpc_service.proto", fileDescriptor_626e658682f5c341) }

var fileDescriptor_626e658682f5c341 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0xa9, 0x87, 0x1e, 0x16, 0x8a, 0x12, 0x51, 0x70, 0xd5, 0x1e, 0xf5, 0x96, 0x80, 0x9e,
	0xbc, 0x08, 0x56, 0xa5, 0xa7, 0x4a, 0x69, 0x3d, 0x79, 0x91, 0x64, 0x9d, 0xcd, 0x46, 0xd3, 0x24,
	0x66, 0x26, 0x82, 0x3e, 0xa1, 0x47, 0xc1, 0x17, 0x90, 0x3e, 0x89, 0x6c, 0xc3, 0x82, 0x14, 0x8a,
	0xc7, 0xf9, 0x66, 0xe6, 0x1b, 0x98, 0xbf, 0x60, 0x3a, 0x86, 0xea, 0x11, 0x21, 0xbe, 0x99, 0x0a,
	0x78, 0x88, 0x9e, 0x3c, 0xeb, 0xb7, 0x2c, 0xa8, 0x72, 0x10, 0x65, 0x4d, 0x13, 0xd4, 0x19, 0x97,
	0x87, 0xda, 0x7b, 0x6d, 0x41, 0xac, 0x2a, 0x95, 0x6a, 0x01, 0x8b, 0x40, 0xef, 0xb9, 0x79, 0xf6,
	0xbd, 0x55, 0x0c, 0x66, 0xb2, 0xa6, 0xfb, 0x28, 0x1d, 0x06, 0x1f, 0x89, 0x5d, 0x16, 0x3b, 0x73,
	0x70, 0x4f, 0x23, 0x49, 0x55, 0x33, 0x01, 0x44, 0xa9, 0x81, 0x31, 0xde, 0x2a, 0xf9, 0x5f, 0x56,
	0xee, 0xf3, 0xec, 0xe5, 0x9d, 0x97, 0xdf, 0xb6, 0x5e, 0x76, 0x53, 0xec, 0xb6, 0xfb, 0x73, 0x27,
	0x03, 0x36, 0x9e, 0x3a, 0xc5, 0x5e, 0x56, 0xac, 0xe1, 0x8d, 0x96, 0xbb, 0x62, 0x7b, 0x0c, 0x74,
	0x6d, 0x13, 0x12, 0xc4, 0x29, 0x40, 0x44, 0x76, 0x94, 0x0d, 0x6b, 0x78, 0x06, 0xaf, 0x09, 0x90,
	0xca, 0xe3, 0x0d, 0x5d, 0x0c, 0xde, 0x21, 0x30, 0x5b, 0x1c, 0x4c, 0x93, 0xb2, 0x06, 0x9b, 0xab,
	0x10, 0xac, 0xa9, 0x24, 0x19, 0xef, 0xe6, 0xf9, 0x7d, 0xec, 0x24, 0xef, 0x6e, 0x1c, 0xe8, 0x6e,
	0x9c, 0xfe, 0x3b, 0x97, 0xaf, 0x8d, 0xc6, 0x9f, 0xcb, 0x61, 0xef, 0x6b, 0x39, 0xec, 0xfd, 0x2c,
	0x87, 0xbd, 0x87, 0x0b, 0x6d, 0xa8, 0x49, 0x8a, 0x57, 0x7e, 0x21, 0x6a, 0xe9, 0x64, 0x7a, 0x36,
	0x20, 0x94, 0x54, 0xe9, 0x43, 0x8a, 0xf0, 0xa2, 0x05, 0x75, 0xbf, 0xcf, 0x11, 0x55, 0xde, 0x8a,
	0x36, 0x49, 0x11, 0x94, 0xea, 0xaf, 0xc8, 0xf9, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xec, 0x62,
	0x97, 0x8b, 0xef, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RaftTransportClient is the client API for RaftTransport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RaftTransportClient interface {
	// SendBatchMessage sends a batch of Raft messages
	SendBatchMessage(ctx context.Context, in *babuzapb.BatchMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// SendSnapshotMessage sends a snapshot message
	SendSnapshotMessage(ctx context.Context, in *babuzapb.SnapshotMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetClusterPeers gets information about peers in the cluster
	GetClusterPeers(ctx context.Context, in *babuzapb.GetClusterPeersRequest, opts ...grpc.CallOption) (*babuzapb.GetClusterPeersResponse, error)
	// PublishApplicationService publishes application service addresses
	PublishApplicationService(ctx context.Context, in *babuzapb.PublishApplicationServiceRequest, opts ...grpc.CallOption) (*babuzapb.PublishApplicationServiceResponse, error)
}

type raftTransportClient struct {
	cc *grpc.ClientConn
}

func NewRaftTransportClient(cc *grpc.ClientConn) RaftTransportClient {
	return &raftTransportClient{cc}
}

func (c *raftTransportClient) SendBatchMessage(ctx context.Context, in *babuzapb.BatchMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/grpcpb.RaftTransport/SendBatchMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftTransportClient) SendSnapshotMessage(ctx context.Context, in *babuzapb.SnapshotMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/grpcpb.RaftTransport/SendSnapshotMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftTransportClient) GetClusterPeers(ctx context.Context, in *babuzapb.GetClusterPeersRequest, opts ...grpc.CallOption) (*babuzapb.GetClusterPeersResponse, error) {
	out := new(babuzapb.GetClusterPeersResponse)
	err := c.cc.Invoke(ctx, "/grpcpb.RaftTransport/GetClusterPeers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftTransportClient) PublishApplicationService(ctx context.Context, in *babuzapb.PublishApplicationServiceRequest, opts ...grpc.CallOption) (*babuzapb.PublishApplicationServiceResponse, error) {
	out := new(babuzapb.PublishApplicationServiceResponse)
	err := c.cc.Invoke(ctx, "/grpcpb.RaftTransport/PublishApplicationService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftTransportServer is the server API for RaftTransport service.
type RaftTransportServer interface {
	// SendBatchMessage sends a batch of Raft messages
	SendBatchMessage(context.Context, *babuzapb.BatchMessage) (*emptypb.Empty, error)
	// SendSnapshotMessage sends a snapshot message
	SendSnapshotMessage(context.Context, *babuzapb.SnapshotMessage) (*emptypb.Empty, error)
	// GetClusterPeers gets information about peers in the cluster
	GetClusterPeers(context.Context, *babuzapb.GetClusterPeersRequest) (*babuzapb.GetClusterPeersResponse, error)
	// PublishApplicationService publishes application service addresses
	PublishApplicationService(context.Context, *babuzapb.PublishApplicationServiceRequest) (*babuzapb.PublishApplicationServiceResponse, error)
}

func RegisterRaftTransportServer(s *grpc.Server, srv RaftTransportServer) {
	s.RegisterService(&_RaftTransport_serviceDesc, srv)
}

func _RaftTransport_SendBatchMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(babuzapb.BatchMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftTransportServer).SendBatchMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcpb.RaftTransport/SendBatchMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftTransportServer).SendBatchMessage(ctx, req.(*babuzapb.BatchMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftTransport_SendSnapshotMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(babuzapb.SnapshotMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftTransportServer).SendSnapshotMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcpb.RaftTransport/SendSnapshotMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftTransportServer).SendSnapshotMessage(ctx, req.(*babuzapb.SnapshotMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftTransport_GetClusterPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(babuzapb.GetClusterPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftTransportServer).GetClusterPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcpb.RaftTransport/GetClusterPeers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftTransportServer).GetClusterPeers(ctx, req.(*babuzapb.GetClusterPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftTransport_PublishApplicationService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(babuzapb.PublishApplicationServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftTransportServer).PublishApplicationService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcpb.RaftTransport/PublishApplicationService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftTransportServer).PublishApplicationService(ctx, req.(*babuzapb.PublishApplicationServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RaftTransport_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcpb.RaftTransport",
	HandlerType: (*RaftTransportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendBatchMessage",
			Handler:    _RaftTransport_SendBatchMessage_Handler,
		},
		{
			MethodName: "SendSnapshotMessage",
			Handler:    _RaftTransport_SendSnapshotMessage_Handler,
		},
		{
			MethodName: "GetClusterPeers",
			Handler:    _RaftTransport_GetClusterPeers_Handler,
		},
		{
			MethodName: "PublishApplicationService",
			Handler:    _RaftTransport_PublishApplicationService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc_service.proto",
}
