// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: grpc_service.proto

package pb

import (
	context "context"
	fmt "fmt"
	babuzapb "github.com/fanaujie/babuza/ibabuza/babuzapb"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

func init() { proto.RegisterFile("grpc_service.proto", fileDescriptor_626e658682f5c341) }

var fileDescriptor_626e658682f5c341 = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x93, 0x31, 0x4b, 0x2b, 0x41,
	0x10, 0xc7, 0xb9, 0x14, 0x29, 0x16, 0xc2, 0x7b, 0xec, 0xe3, 0x09, 0x9e, 0x9a, 0x52, 0xad, 0x76,
	0x25, 0x56, 0x36, 0x82, 0x51, 0x49, 0x15, 0x09, 0x89, 0x95, 0x8d, 0xec, 0x9e, 0x73, 0x7b, 0xab,
	0x9b, 0xdb, 0x75, 0x77, 0x56, 0xd0, 0x4f, 0x68, 0x29, 0xd8, 0x5a, 0x48, 0x3e, 0x89, 0x5c, 0x96,
	0x03, 0x0d, 0x04, 0x0b, 0x5b, 0xcb, 0xf9, 0xcd, 0xcc, 0x6f, 0xe0, 0x0f, 0x43, 0xa8, 0xf2, 0xae,
	0xb8, 0x0e, 0xe0, 0x1f, 0x74, 0x01, 0xcc, 0x79, 0x8b, 0x96, 0x76, 0x1b, 0xe6, 0x64, 0xde, 0xf3,
	0xa2, 0xc4, 0x71, 0x50, 0x09, 0xe7, 0x5b, 0xca, 0x5a, 0x65, 0x80, 0x2f, 0x2b, 0x19, 0x4b, 0x0e,
	0x73, 0x87, 0x8f, 0xa9, 0x39, 0x78, 0xed, 0x90, 0xde, 0x54, 0x94, 0x78, 0xe9, 0x45, 0x1d, 0x9c,
	0xf5, 0x48, 0x8f, 0xc9, 0xdf, 0x19, 0xd4, 0x37, 0x43, 0x81, 0x45, 0x35, 0x86, 0x10, 0x84, 0x02,
	0x4a, 0x59, 0xa3, 0x64, 0x9f, 0x59, 0xbe, 0xc1, 0x92, 0x97, 0xb5, 0x5e, 0x76, 0xde, 0x78, 0xe9,
	0x19, 0xf9, 0xd7, 0xec, 0xcf, 0x6a, 0xe1, 0x42, 0x65, 0xb1, 0x55, 0xfc, 0x4f, 0x8a, 0x15, 0xbc,
	0xd6, 0x72, 0x41, 0xfe, 0x8c, 0x00, 0x4f, 0x4d, 0x0c, 0x08, 0x7e, 0x02, 0xe0, 0x03, 0xdd, 0x4e,
	0x86, 0x15, 0x3c, 0x85, 0xfb, 0x08, 0x01, 0xf3, 0x9d, 0x35, 0xdd, 0xe0, 0x6c, 0x1d, 0x80, 0x1a,
	0xb2, 0x39, 0x89, 0xd2, 0xe8, 0x50, 0x9d, 0x38, 0x67, 0x74, 0x21, 0x50, 0xdb, 0x7a, 0x96, 0xe2,
	0xa3, 0xbb, 0x69, 0x77, 0xed, 0x40, 0x7b, 0x63, 0xef, 0xdb, 0xb9, 0x74, 0x6d, 0xf0, 0xd6, 0x21,
	0x74, 0x1c, 0x0d, 0xea, 0xaf, 0xd1, 0x0e, 0x7f, 0x16, 0xed, 0x7e, 0x76, 0x90, 0xfd, 0xc6, 0x1b,
	0x60, 0x38, 0x7a, 0x5e, 0xf4, 0xb3, 0x97, 0x45, 0x3f, 0x7b, 0x5f, 0xf4, 0xb3, 0xab, 0x23, 0xa5,
	0xb1, 0x8a, 0x92, 0x15, 0x76, 0xce, 0x4b, 0x51, 0x8b, 0x78, 0xab, 0x81, 0x4b, 0x21, 0xe3, 0x93,
	0xe0, 0xee, 0x4e, 0x71, 0x6c, 0xf3, 0x4f, 0x1f, 0x50, 0x58, 0xc3, 0x9b, 0x47, 0xe1, 0x4e, 0xca,
	0xee, 0x92, 0x1c, 0x7e, 0x04, 0x00, 0x00, 0xff, 0xff, 0x12, 0x17, 0x34, 0xb8, 0x4e, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RaftTransportClient is the client API for RaftTransport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RaftTransportClient interface {
	// SendBatchMessage sends a batch of Raft messages
	SendBatchMessage(ctx context.Context, in *babuzapb.BatchMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// SendSnapshotMessage sends a snapshot message
	SendSnapshotMessage(ctx context.Context, in *babuzapb.SnapshotMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetClusterPeers gets information about peers in the cluster
	GetClusterPeers(ctx context.Context, in *babuzapb.GetClusterPeersRequest, opts ...grpc.CallOption) (*babuzapb.GetClusterPeersResponse, error)
	// PublishApplicationService publishes application service addresses
	PublishApplicationService(ctx context.Context, in *babuzapb.PublishApplicationServiceRequest, opts ...grpc.CallOption) (*babuzapb.PublishApplicationServiceResponse, error)
}

type raftTransportClient struct {
	cc *grpc.ClientConn
}

func NewRaftTransportClient(cc *grpc.ClientConn) RaftTransportClient {
	return &raftTransportClient{cc}
}

func (c *raftTransportClient) SendBatchMessage(ctx context.Context, in *babuzapb.BatchMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/grpcpb.RaftTransport/SendBatchMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftTransportClient) SendSnapshotMessage(ctx context.Context, in *babuzapb.SnapshotMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/grpcpb.RaftTransport/SendSnapshotMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftTransportClient) GetClusterPeers(ctx context.Context, in *babuzapb.GetClusterPeersRequest, opts ...grpc.CallOption) (*babuzapb.GetClusterPeersResponse, error) {
	out := new(babuzapb.GetClusterPeersResponse)
	err := c.cc.Invoke(ctx, "/grpcpb.RaftTransport/GetClusterPeers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftTransportClient) PublishApplicationService(ctx context.Context, in *babuzapb.PublishApplicationServiceRequest, opts ...grpc.CallOption) (*babuzapb.PublishApplicationServiceResponse, error) {
	out := new(babuzapb.PublishApplicationServiceResponse)
	err := c.cc.Invoke(ctx, "/grpcpb.RaftTransport/PublishApplicationService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftTransportServer is the server API for RaftTransport service.
type RaftTransportServer interface {
	// SendBatchMessage sends a batch of Raft messages
	SendBatchMessage(context.Context, *babuzapb.BatchMessage) (*emptypb.Empty, error)
	// SendSnapshotMessage sends a snapshot message
	SendSnapshotMessage(context.Context, *babuzapb.SnapshotMessage) (*emptypb.Empty, error)
	// GetClusterPeers gets information about peers in the cluster
	GetClusterPeers(context.Context, *babuzapb.GetClusterPeersRequest) (*babuzapb.GetClusterPeersResponse, error)
	// PublishApplicationService publishes application service addresses
	PublishApplicationService(context.Context, *babuzapb.PublishApplicationServiceRequest) (*babuzapb.PublishApplicationServiceResponse, error)
}

func RegisterRaftTransportServer(s *grpc.Server, srv RaftTransportServer) {
	s.RegisterService(&_RaftTransport_serviceDesc, srv)
}

func _RaftTransport_SendBatchMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(babuzapb.BatchMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftTransportServer).SendBatchMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcpb.RaftTransport/SendBatchMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftTransportServer).SendBatchMessage(ctx, req.(*babuzapb.BatchMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftTransport_SendSnapshotMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(babuzapb.SnapshotMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftTransportServer).SendSnapshotMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcpb.RaftTransport/SendSnapshotMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftTransportServer).SendSnapshotMessage(ctx, req.(*babuzapb.SnapshotMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftTransport_GetClusterPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(babuzapb.GetClusterPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftTransportServer).GetClusterPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcpb.RaftTransport/GetClusterPeers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftTransportServer).GetClusterPeers(ctx, req.(*babuzapb.GetClusterPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftTransport_PublishApplicationService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(babuzapb.PublishApplicationServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftTransportServer).PublishApplicationService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcpb.RaftTransport/PublishApplicationService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftTransportServer).PublishApplicationService(ctx, req.(*babuzapb.PublishApplicationServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RaftTransport_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcpb.RaftTransport",
	HandlerType: (*RaftTransportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendBatchMessage",
			Handler:    _RaftTransport_SendBatchMessage_Handler,
		},
		{
			MethodName: "SendSnapshotMessage",
			Handler:    _RaftTransport_SendSnapshotMessage_Handler,
		},
		{
			MethodName: "GetClusterPeers",
			Handler:    _RaftTransport_GetClusterPeers_Handler,
		},
		{
			MethodName: "PublishApplicationService",
			Handler:    _RaftTransport_PublishApplicationService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc_service.proto",
}

// MultiRaftTransportClient is the client API for MultiRaftTransport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MultiRaftTransportClient interface {
	// SendBatchMessage sends stream of batch messages
	SendBatchMessage(ctx context.Context, opts ...grpc.CallOption) (MultiRaftTransport_SendBatchMessageClient, error)
	// SendSnapshotMessage sends a snapshot message
	SendSnapshotMessage(ctx context.Context, in *babuzapb.SnapshotMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetClusterPeers gets information about peers in the cluster
	GetClusterPeers(ctx context.Context, in *babuzapb.GetClusterPeersRequest, opts ...grpc.CallOption) (*babuzapb.GetClusterPeersResponse, error)
	// PublishApplicationService publishes application service addresses
	PublishApplicationService(ctx context.Context, in *babuzapb.PublishApplicationServiceRequest, opts ...grpc.CallOption) (*babuzapb.PublishApplicationServiceResponse, error)
}

type multiRaftTransportClient struct {
	cc *grpc.ClientConn
}

func NewMultiRaftTransportClient(cc *grpc.ClientConn) MultiRaftTransportClient {
	return &multiRaftTransportClient{cc}
}

func (c *multiRaftTransportClient) SendBatchMessage(ctx context.Context, opts ...grpc.CallOption) (MultiRaftTransport_SendBatchMessageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MultiRaftTransport_serviceDesc.Streams[0], "/grpcpb.MultiRaftTransport/SendBatchMessage", opts...)
	if err != nil {
		return nil, err
	}
	x := &multiRaftTransportSendBatchMessageClient{stream}
	return x, nil
}

type MultiRaftTransport_SendBatchMessageClient interface {
	Send(*babuzapb.BatchMessage) error
	Recv() (*emptypb.Empty, error)
	grpc.ClientStream
}

type multiRaftTransportSendBatchMessageClient struct {
	grpc.ClientStream
}

func (x *multiRaftTransportSendBatchMessageClient) Send(m *babuzapb.BatchMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *multiRaftTransportSendBatchMessageClient) Recv() (*emptypb.Empty, error) {
	m := new(emptypb.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *multiRaftTransportClient) SendSnapshotMessage(ctx context.Context, in *babuzapb.SnapshotMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/grpcpb.MultiRaftTransport/SendSnapshotMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiRaftTransportClient) GetClusterPeers(ctx context.Context, in *babuzapb.GetClusterPeersRequest, opts ...grpc.CallOption) (*babuzapb.GetClusterPeersResponse, error) {
	out := new(babuzapb.GetClusterPeersResponse)
	err := c.cc.Invoke(ctx, "/grpcpb.MultiRaftTransport/GetClusterPeers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiRaftTransportClient) PublishApplicationService(ctx context.Context, in *babuzapb.PublishApplicationServiceRequest, opts ...grpc.CallOption) (*babuzapb.PublishApplicationServiceResponse, error) {
	out := new(babuzapb.PublishApplicationServiceResponse)
	err := c.cc.Invoke(ctx, "/grpcpb.MultiRaftTransport/PublishApplicationService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MultiRaftTransportServer is the server API for MultiRaftTransport service.
type MultiRaftTransportServer interface {
	// SendBatchMessage sends stream of batch messages
	SendBatchMessage(MultiRaftTransport_SendBatchMessageServer) error
	// SendSnapshotMessage sends a snapshot message
	SendSnapshotMessage(context.Context, *babuzapb.SnapshotMessage) (*emptypb.Empty, error)
	// GetClusterPeers gets information about peers in the cluster
	GetClusterPeers(context.Context, *babuzapb.GetClusterPeersRequest) (*babuzapb.GetClusterPeersResponse, error)
	// PublishApplicationService publishes application service addresses
	PublishApplicationService(context.Context, *babuzapb.PublishApplicationServiceRequest) (*babuzapb.PublishApplicationServiceResponse, error)
}

func RegisterMultiRaftTransportServer(s *grpc.Server, srv MultiRaftTransportServer) {
	s.RegisterService(&_MultiRaftTransport_serviceDesc, srv)
}

func _MultiRaftTransport_SendBatchMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MultiRaftTransportServer).SendBatchMessage(&multiRaftTransportSendBatchMessageServer{stream})
}

type MultiRaftTransport_SendBatchMessageServer interface {
	Send(*emptypb.Empty) error
	Recv() (*babuzapb.BatchMessage, error)
	grpc.ServerStream
}

type multiRaftTransportSendBatchMessageServer struct {
	grpc.ServerStream
}

func (x *multiRaftTransportSendBatchMessageServer) Send(m *emptypb.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *multiRaftTransportSendBatchMessageServer) Recv() (*babuzapb.BatchMessage, error) {
	m := new(babuzapb.BatchMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _MultiRaftTransport_SendSnapshotMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(babuzapb.SnapshotMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiRaftTransportServer).SendSnapshotMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcpb.MultiRaftTransport/SendSnapshotMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiRaftTransportServer).SendSnapshotMessage(ctx, req.(*babuzapb.SnapshotMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiRaftTransport_GetClusterPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(babuzapb.GetClusterPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiRaftTransportServer).GetClusterPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcpb.MultiRaftTransport/GetClusterPeers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiRaftTransportServer).GetClusterPeers(ctx, req.(*babuzapb.GetClusterPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiRaftTransport_PublishApplicationService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(babuzapb.PublishApplicationServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiRaftTransportServer).PublishApplicationService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcpb.MultiRaftTransport/PublishApplicationService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiRaftTransportServer).PublishApplicationService(ctx, req.(*babuzapb.PublishApplicationServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MultiRaftTransport_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcpb.MultiRaftTransport",
	HandlerType: (*MultiRaftTransportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendSnapshotMessage",
			Handler:    _MultiRaftTransport_SendSnapshotMessage_Handler,
		},
		{
			MethodName: "GetClusterPeers",
			Handler:    _MultiRaftTransport_GetClusterPeers_Handler,
		},
		{
			MethodName: "PublishApplicationService",
			Handler:    _MultiRaftTransport_PublishApplicationService_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendBatchMessage",
			Handler:       _MultiRaftTransport_SendBatchMessage_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpc_service.proto",
}
