syntax = "proto3";
package grpcpb;
option go_package = "github.com/fanaujie/babuza/pkg/transport/protocol/grpc/pb";


import "raftMsg.proto";
import "google/protobuf/empty.proto";


// RaftTransport service defines the gRPC operations for Raft communication
service RaftTransport {
  // SendBatchMessage sends a batch of Raft messages
  rpc SendBatchMessage(raft.BatchMessage) returns (google.protobuf.Empty);
  
  // SendSnapshotMessage sends a snapshot message
  rpc SendSnapshotMessage(raft.SnapshotMessage) returns (raft.SnapshotMessageResponse);
  
  // GetClusterPeers gets information about peers in the cluster
  rpc GetClusterPeers(raft.GetClusterPeersRequest) returns (raft.GetClusterPeersResponse);
  
  // PublishApplicationService publishes application service addresses
  rpc PublishApplicationService(raft.PublishApplicationServiceRequest) returns (raft.PublishApplicationServiceResponse);
}


service MultiRaftTransport {
  // SendBatchMessage sends stream of batch messages
  rpc SendMultiRaftMessage(stream raft.MultiRaftBatchMessage) returns (stream google.protobuf.Empty);

  // SendSnapshotMessage sends a snapshot message
  rpc SendSnapshotMessage(raft.SnapshotMessage) returns (raft.SnapshotMessageResponse);

  // GetClusterPeers gets information about peers in the cluster
  rpc GetClusterPeers(raft.GetClusterPeersRequest) returns (raft.GetClusterPeersResponse);

  // PublishApplicationService publishes application service addresses
  rpc PublishApplicationService(raft.PublishApplicationServiceRequest) returns (raft.PublishApplicationServiceResponse);
}