// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: babuza.proto

package babuzapb

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	raftpb "go.etcd.io/etcd/raft/v3/raftpb"
	io "io"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type SnapshotFileCompressionType int32

const (
	SnapshotFileCompression_None   SnapshotFileCompressionType = 0
	SnapshotFileCompression_Snappy SnapshotFileCompressionType = 1
)

var SnapshotFileCompressionType_name = map[int32]string{
	0: "SnapshotFileCompression_None",
	1: "SnapshotFileCompression_Snappy",
}

var SnapshotFileCompressionType_value = map[string]int32{
	"SnapshotFileCompression_None":   0,
	"SnapshotFileCompression_Snappy": 1,
}

func (x SnapshotFileCompressionType) String() string {
	return proto.EnumName(SnapshotFileCompressionType_name, int32(x))
}

func (SnapshotFileCompressionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ec888774afb62ec3, []int{0}
}

type SnapshotFileType int32

const (
	SnapshotFileType_Cluster      SnapshotFileType = 0
	SnapshotFileType_Session      SnapshotFileType = 1
	SnapshotFileType_StateMachine SnapshotFileType = 2
	SnapshotFileType_Metadata     SnapshotFileType = 3
)

var SnapshotFileType_name = map[int32]string{
	0: "SnapshotFileType_Cluster",
	1: "SnapshotFileType_Session",
	2: "SnapshotFileType_StateMachine",
	3: "SnapshotFileType_Metadata",
}

var SnapshotFileType_value = map[string]int32{
	"SnapshotFileType_Cluster":      0,
	"SnapshotFileType_Session":      1,
	"SnapshotFileType_StateMachine": 2,
	"SnapshotFileType_Metadata":     3,
}

func (x SnapshotFileType) String() string {
	return proto.EnumName(SnapshotFileType_name, int32(x))
}

func (SnapshotFileType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ec888774afb62ec3, []int{1}
}

type SnapshotFolderType int32

const (
	SnapshotFolderType_InstallSnapshot SnapshotFolderType = 0
	SnapshotFolderType_TempWrite       SnapshotFolderType = 1
	SnapshotFolderType_TempReceive     SnapshotFolderType = 2
)

var SnapshotFolderType_name = map[int32]string{
	0: "SnapshotFolderType_InstallSnapshot",
	1: "SnapshotFolderType_TempWrite",
	2: "SnapshotFolderType_TempReceive",
}

var SnapshotFolderType_value = map[string]int32{
	"SnapshotFolderType_InstallSnapshot": 0,
	"SnapshotFolderType_TempWrite":       1,
	"SnapshotFolderType_TempReceive":     2,
}

func (x SnapshotFolderType) String() string {
	return proto.EnumName(SnapshotFolderType_name, int32(x))
}

func (SnapshotFolderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ec888774afb62ec3, []int{2}
}

type RaftPeerAttribute struct {
	Id             uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RaftListenAddr string `protobuf:"bytes,2,opt,name=raftListenAddr,proto3" json:"raftListenAddr,omitempty"`
	IsLearner      bool   `protobuf:"varint,3,opt,name=isLearner,proto3" json:"isLearner,omitempty"`
}

func (m *RaftPeerAttribute) Reset()         { *m = RaftPeerAttribute{} }
func (m *RaftPeerAttribute) String() string { return proto.CompactTextString(m) }
func (*RaftPeerAttribute) ProtoMessage()    {}
func (*RaftPeerAttribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec888774afb62ec3, []int{0}
}
func (m *RaftPeerAttribute) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RaftPeerAttribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RaftPeerAttribute.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RaftPeerAttribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RaftPeerAttribute.Merge(m, src)
}
func (m *RaftPeerAttribute) XXX_Size() int {
	return m.Size()
}
func (m *RaftPeerAttribute) XXX_DiscardUnknown() {
	xxx_messageInfo_RaftPeerAttribute.DiscardUnknown(m)
}

var xxx_messageInfo_RaftPeerAttribute proto.InternalMessageInfo

type Peer struct {
	RaftPeerAttr        RaftPeerAttribute `protobuf:"bytes,1,opt,name=raftPeerAttr,proto3" json:"raftPeerAttr"`
	AppServiceAddresses []string          `protobuf:"bytes,2,rep,name=appServiceAddresses,proto3" json:"appServiceAddresses,omitempty"`
}

func (m *Peer) Reset()         { *m = Peer{} }
func (m *Peer) String() string { return proto.CompactTextString(m) }
func (*Peer) ProtoMessage()    {}
func (*Peer) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec888774afb62ec3, []int{1}
}
func (m *Peer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Peer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Peer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Peer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Peer.Merge(m, src)
}
func (m *Peer) XXX_Size() int {
	return m.Size()
}
func (m *Peer) XXX_DiscardUnknown() {
	xxx_messageInfo_Peer.DiscardUnknown(m)
}

var xxx_messageInfo_Peer proto.InternalMessageInfo

type SnapshotFileDesc struct {
	FileType        SnapshotFileType            `protobuf:"varint,1,opt,name=fileType,proto3,enum=babuza.SnapshotFileType" json:"fileType,omitempty"`
	CompressionType SnapshotFileCompressionType `protobuf:"varint,2,opt,name=compressionType,proto3,enum=babuza.SnapshotFileCompressionType" json:"compressionType,omitempty"`
	Tag             string                      `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	FileSize        int64                       `protobuf:"varint,4,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	FileCrc64       uint64                      `protobuf:"varint,5,opt,name=fileCrc64,proto3" json:"fileCrc64,omitempty"`
	Metadata        []byte                      `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (m *SnapshotFileDesc) Reset()         { *m = SnapshotFileDesc{} }
func (m *SnapshotFileDesc) String() string { return proto.CompactTextString(m) }
func (*SnapshotFileDesc) ProtoMessage()    {}
func (*SnapshotFileDesc) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec888774afb62ec3, []int{2}
}
func (m *SnapshotFileDesc) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SnapshotFileDesc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SnapshotFileDesc.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SnapshotFileDesc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotFileDesc.Merge(m, src)
}
func (m *SnapshotFileDesc) XXX_Size() int {
	return m.Size()
}
func (m *SnapshotFileDesc) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotFileDesc.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotFileDesc proto.InternalMessageInfo

type SnapshotMetadata struct {
	Version  uint64                      `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Snapshot raftpb.Snapshot             `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot"`
	Files    map[string]SnapshotFileDesc `protobuf:"bytes,3,rep,name=files,proto3" json:"files" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *SnapshotMetadata) Reset()         { *m = SnapshotMetadata{} }
func (m *SnapshotMetadata) String() string { return proto.CompactTextString(m) }
func (*SnapshotMetadata) ProtoMessage()    {}
func (*SnapshotMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec888774afb62ec3, []int{3}
}
func (m *SnapshotMetadata) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SnapshotMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SnapshotMetadata.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SnapshotMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotMetadata.Merge(m, src)
}
func (m *SnapshotMetadata) XXX_Size() int {
	return m.Size()
}
func (m *SnapshotMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotMetadata proto.InternalMessageInfo

type RegisterSessionRequest struct {
}

func (m *RegisterSessionRequest) Reset()         { *m = RegisterSessionRequest{} }
func (m *RegisterSessionRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterSessionRequest) ProtoMessage()    {}
func (*RegisterSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec888774afb62ec3, []int{4}
}
func (m *RegisterSessionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RegisterSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RegisterSessionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RegisterSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterSessionRequest.Merge(m, src)
}
func (m *RegisterSessionRequest) XXX_Size() int {
	return m.Size()
}
func (m *RegisterSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterSessionRequest proto.InternalMessageInfo

type PubAppServiceRequest struct {
	PubServicePeerID    uint64   `protobuf:"varint,1,opt,name=pubServicePeerID,proto3" json:"pubServicePeerID,omitempty"`
	AppServiceAddresses []string `protobuf:"bytes,3,rep,name=appServiceAddresses,proto3" json:"appServiceAddresses,omitempty"`
}

func (m *PubAppServiceRequest) Reset()         { *m = PubAppServiceRequest{} }
func (m *PubAppServiceRequest) String() string { return proto.CompactTextString(m) }
func (*PubAppServiceRequest) ProtoMessage()    {}
func (*PubAppServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec888774afb62ec3, []int{5}
}
func (m *PubAppServiceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PubAppServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PubAppServiceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PubAppServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubAppServiceRequest.Merge(m, src)
}
func (m *PubAppServiceRequest) XXX_Size() int {
	return m.Size()
}
func (m *PubAppServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PubAppServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PubAppServiceRequest proto.InternalMessageInfo

type RequestContext struct {
	ReplyID                   uint64 `protobuf:"varint,1,opt,name=replyID,proto3" json:"replyID,omitempty"`
	SessionID                 uint64 `protobuf:"varint,2,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	SequenceNum               uint64 `protobuf:"varint,3,opt,name=sequenceNum,proto3" json:"sequenceNum,omitempty"`
	LowestSeqNumNotYetReplied uint64 `protobuf:"varint,4,opt,name=lowestSeqNumNotYetReplied,proto3" json:"lowestSeqNumNotYetReplied,omitempty"`
}

func (m *RequestContext) Reset()         { *m = RequestContext{} }
func (m *RequestContext) String() string { return proto.CompactTextString(m) }
func (*RequestContext) ProtoMessage()    {}
func (*RequestContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec888774afb62ec3, []int{6}
}
func (m *RequestContext) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RequestContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RequestContext.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RequestContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestContext.Merge(m, src)
}
func (m *RequestContext) XXX_Size() int {
	return m.Size()
}
func (m *RequestContext) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestContext.DiscardUnknown(m)
}

var xxx_messageInfo_RequestContext proto.InternalMessageInfo

type NormalRequest struct {
	Context         RequestContext          `protobuf:"bytes,1,opt,name=context,proto3" json:"context"`
	Register        *RegisterSessionRequest `protobuf:"bytes,2,opt,name=register,proto3" json:"register,omitempty"`
	PubAppService   *PubAppServiceRequest   `protobuf:"bytes,3,opt,name=pubAppService,proto3" json:"pubAppService,omitempty"`
	StateMachineLog []byte                  `protobuf:"bytes,4,opt,name=stateMachineLog,proto3" json:"stateMachineLog,omitempty"`
}

func (m *NormalRequest) Reset()         { *m = NormalRequest{} }
func (m *NormalRequest) String() string { return proto.CompactTextString(m) }
func (*NormalRequest) ProtoMessage()    {}
func (*NormalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec888774afb62ec3, []int{7}
}
func (m *NormalRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NormalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NormalRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NormalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NormalRequest.Merge(m, src)
}
func (m *NormalRequest) XXX_Size() int {
	return m.Size()
}
func (m *NormalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NormalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NormalRequest proto.InternalMessageInfo

type ConfChangeRequest struct {
	Context        RequestContext    `protobuf:"bytes,1,opt,name=context,proto3" json:"context"`
	RaftPeerAttr   RaftPeerAttribute `protobuf:"bytes,2,opt,name=raftPeerAttr,proto3" json:"raftPeerAttr"`
	PromoteLearner bool              `protobuf:"varint,3,opt,name=promoteLearner,proto3" json:"promoteLearner,omitempty"`
}

func (m *ConfChangeRequest) Reset()         { *m = ConfChangeRequest{} }
func (m *ConfChangeRequest) String() string { return proto.CompactTextString(m) }
func (*ConfChangeRequest) ProtoMessage()    {}
func (*ConfChangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec888774afb62ec3, []int{8}
}
func (m *ConfChangeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConfChangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConfChangeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConfChangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfChangeRequest.Merge(m, src)
}
func (m *ConfChangeRequest) XXX_Size() int {
	return m.Size()
}
func (m *ConfChangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfChangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfChangeRequest proto.InternalMessageInfo

type WalMetadata struct {
	ClusterID   uint64 `protobuf:"varint,1,opt,name=clusterID,proto3" json:"clusterID,omitempty"`
	LocalPeerID uint64 `protobuf:"varint,2,opt,name=localPeerID,proto3" json:"localPeerID,omitempty"`
}

func (m *WalMetadata) Reset()         { *m = WalMetadata{} }
func (m *WalMetadata) String() string { return proto.CompactTextString(m) }
func (*WalMetadata) ProtoMessage()    {}
func (*WalMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec888774afb62ec3, []int{9}
}
func (m *WalMetadata) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WalMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WalMetadata.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WalMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalMetadata.Merge(m, src)
}
func (m *WalMetadata) XXX_Size() int {
	return m.Size()
}
func (m *WalMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_WalMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_WalMetadata proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("babuza.SnapshotFileCompressionType", SnapshotFileCompressionType_name, SnapshotFileCompressionType_value)
	proto.RegisterEnum("babuza.SnapshotFileType", SnapshotFileType_name, SnapshotFileType_value)
	proto.RegisterEnum("babuza.SnapshotFolderType", SnapshotFolderType_name, SnapshotFolderType_value)
	proto.RegisterType((*RaftPeerAttribute)(nil), "babuza.RaftPeerAttribute")
	proto.RegisterType((*Peer)(nil), "babuza.Peer")
	proto.RegisterType((*SnapshotFileDesc)(nil), "babuza.SnapshotFileDesc")
	proto.RegisterType((*SnapshotMetadata)(nil), "babuza.SnapshotMetadata")
	proto.RegisterMapType((map[string]SnapshotFileDesc)(nil), "babuza.SnapshotMetadata.FilesEntry")
	proto.RegisterType((*RegisterSessionRequest)(nil), "babuza.RegisterSessionRequest")
	proto.RegisterType((*PubAppServiceRequest)(nil), "babuza.PubAppServiceRequest")
	proto.RegisterType((*RequestContext)(nil), "babuza.RequestContext")
	proto.RegisterType((*NormalRequest)(nil), "babuza.NormalRequest")
	proto.RegisterType((*ConfChangeRequest)(nil), "babuza.ConfChangeRequest")
	proto.RegisterType((*WalMetadata)(nil), "babuza.WalMetadata")
}

func init() { proto.RegisterFile("babuza.proto", fileDescriptor_ec888774afb62ec3) }

var fileDescriptor_ec888774afb62ec3 = []byte{
	// 928 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xf6, 0xda, 0x4e, 0x1a, 0x1f, 0xa7, 0xe9, 0x76, 0xa8, 0xaa, 0x4d, 0x48, 0x17, 0xb3, 0x48,
	0x91, 0x15, 0x24, 0x1b, 0x85, 0xaa, 0x42, 0x15, 0x12, 0x4a, 0x1c, 0x90, 0x22, 0xc5, 0x56, 0x35,
	0xae, 0x54, 0xc1, 0x4d, 0x34, 0x5e, 0x1f, 0x3b, 0x03, 0xeb, 0x9d, 0xed, 0xec, 0x6c, 0xc0, 0x95,
	0xb8, 0xe1, 0x09, 0xfa, 0x18, 0x3c, 0x02, 0x8f, 0x90, 0xcb, 0x5c, 0x72, 0x85, 0x68, 0xf2, 0x04,
	0x5c, 0x70, 0x0d, 0x9a, 0xd9, 0xf5, 0xfa, 0x9f, 0x0b, 0x7a, 0xe3, 0x99, 0xf9, 0xce, 0x39, 0x73,
	0x7e, 0xbe, 0x6f, 0xc7, 0xb0, 0xdd, 0x63, 0xbd, 0xe4, 0x0d, 0x6b, 0x44, 0x52, 0x28, 0x41, 0x36,
	0xd3, 0xd3, 0xde, 0xc1, 0x50, 0x34, 0x50, 0xf9, 0xfd, 0x06, 0x17, 0x4d, 0xbd, 0x36, 0x25, 0x1b,
	0x28, 0xf3, 0x13, 0xf5, 0xcc, 0x92, 0xfa, 0xef, 0x3d, 0x1a, 0x8a, 0xa1, 0x30, 0xdb, 0xa6, 0xde,
	0xa5, 0xa8, 0xc7, 0xe1, 0x21, 0x65, 0x03, 0xf5, 0x02, 0x51, 0x1e, 0x2b, 0x25, 0x79, 0x2f, 0x51,
	0x48, 0x76, 0xa0, 0xc8, 0xfb, 0x8e, 0x55, 0xb3, 0xea, 0x65, 0x5a, 0xe4, 0x7d, 0x72, 0x00, 0x3b,
	0xfa, 0xa2, 0x73, 0x1e, 0x2b, 0x0c, 0x8f, 0xfb, 0x7d, 0xe9, 0x14, 0x6b, 0x56, 0xbd, 0x42, 0x17,
	0x50, 0xb2, 0x0f, 0x15, 0x1e, 0x9f, 0x23, 0x93, 0x21, 0x4a, 0xa7, 0x54, 0xb3, 0xea, 0x5b, 0x74,
	0x0a, 0x78, 0x3f, 0x43, 0x59, 0xa7, 0x21, 0x2d, 0xd8, 0x96, 0x33, 0x29, 0x4d, 0x9e, 0xea, 0xd1,
	0x6e, 0x23, 0xeb, 0x6e, 0xa9, 0x9c, 0x93, 0xf2, 0xf5, 0x1f, 0x1f, 0x15, 0xe8, 0x5c, 0x10, 0xf9,
	0x0c, 0x3e, 0x60, 0x51, 0xd4, 0x45, 0x79, 0xc5, 0x7d, 0xd4, 0xc9, 0x31, 0x8e, 0x31, 0x76, 0x8a,
	0xb5, 0x52, 0xbd, 0x42, 0x57, 0x99, 0xbc, 0x7f, 0x2c, 0xb0, 0xbb, 0x21, 0x8b, 0xe2, 0x4b, 0xa1,
	0xbe, 0xe1, 0x01, 0x9e, 0x62, 0xec, 0x93, 0xa7, 0xb0, 0x35, 0xe0, 0x01, 0xbe, 0x1c, 0x47, 0x68,
	0xea, 0xd8, 0x39, 0x72, 0x26, 0x75, 0xcc, 0xfa, 0x6a, 0x3b, 0xcd, 0x3d, 0x49, 0x1b, 0x1e, 0xf8,
	0x62, 0x14, 0xe9, 0x8b, 0xb9, 0x08, 0x4d, 0x70, 0xd1, 0x04, 0x7f, 0xb2, 0x2a, 0xb8, 0x35, 0xef,
	0x4a, 0x17, 0x63, 0x89, 0x0d, 0x25, 0xc5, 0x86, 0x66, 0x60, 0x15, 0xaa, 0xb7, 0x64, 0x2f, 0x2d,
	0xab, 0xcb, 0xdf, 0xa0, 0x53, 0xae, 0x59, 0xf5, 0x12, 0xcd, 0xcf, 0x7a, 0xc8, 0x7a, 0xdf, 0x92,
	0xfe, 0xb3, 0xa7, 0xce, 0x86, 0xe1, 0x68, 0x0a, 0xe8, 0xc8, 0x11, 0x2a, 0xd6, 0x67, 0x8a, 0x39,
	0x9b, 0x35, 0xab, 0xbe, 0x4d, 0xf3, 0xb3, 0xf7, 0xf7, 0xcc, 0x04, 0xda, 0x19, 0x48, 0x1c, 0xb8,
	0x77, 0x85, 0x52, 0xd7, 0x92, 0x11, 0x3e, 0x39, 0x92, 0x23, 0xd8, 0x8a, 0x33, 0x6f, 0xd3, 0x5e,
	0xf5, 0xc8, 0x6e, 0xa4, 0xb2, 0xca, 0xdb, 0xcb, 0xa8, 0xc9, 0xfd, 0xc8, 0x57, 0xb0, 0xa1, 0x6b,
	0x89, 0x9d, 0x52, 0xad, 0x54, 0xaf, 0x2e, 0xcf, 0x63, 0x92, 0xb6, 0xa1, 0x07, 0x13, 0x7f, 0x1d,
	0x2a, 0x39, 0xce, 0xee, 0x48, 0xe3, 0xf6, 0x28, 0xc0, 0xd4, 0xa4, 0x27, 0xf3, 0x03, 0x8e, 0x4d,
	0x61, 0x15, 0xaa, 0xb7, 0xa4, 0x01, 0x1b, 0x57, 0x2c, 0x48, 0x30, 0xab, 0x68, 0x25, 0x5b, 0x9a,
	0x59, 0x9a, 0xba, 0x3d, 0x2f, 0x7e, 0x61, 0x79, 0x0e, 0x3c, 0xa6, 0x38, 0xd4, 0x32, 0x95, 0xdd,
	0x74, 0xec, 0x14, 0x5f, 0x27, 0x18, 0x2b, 0x4f, 0xc1, 0xa3, 0x17, 0x49, 0xef, 0x38, 0x57, 0x4b,
	0x86, 0x93, 0x43, 0xb0, 0xa3, 0xa4, 0x97, 0x81, 0x5a, 0x73, 0x67, 0xa7, 0xd9, 0x74, 0x96, 0xf0,
	0x75, 0x4a, 0x2c, 0xad, 0x57, 0xe2, 0xaf, 0x16, 0xec, 0x64, 0x99, 0x5a, 0x22, 0x54, 0xf8, 0x93,
	0xd2, 0x2c, 0x48, 0x8c, 0x82, 0x71, 0x9e, 0x67, 0x72, 0xd4, 0x74, 0xc7, 0x69, 0xd1, 0x67, 0xa7,
	0xa6, 0xe9, 0x32, 0x9d, 0x02, 0xa4, 0x06, 0xd5, 0x58, 0xdf, 0x14, 0xfa, 0xd8, 0x49, 0x46, 0x46,
	0x42, 0x65, 0x3a, 0x0b, 0x91, 0x2f, 0x61, 0x37, 0x10, 0x3f, 0x62, 0xac, 0xba, 0xf8, 0xba, 0x93,
	0x8c, 0x3a, 0x42, 0x7d, 0x8b, 0x8a, 0x62, 0x14, 0x70, 0xec, 0x1b, 0x6d, 0x95, 0xe9, 0x7a, 0x07,
	0xef, 0x2f, 0x0b, 0xee, 0x77, 0x84, 0x1c, 0xb1, 0x60, 0x32, 0x9a, 0x67, 0x70, 0xcf, 0x4f, 0x8b,
	0xce, 0x3e, 0xdc, 0xc7, 0xf9, 0x87, 0x3b, 0xd7, 0x52, 0x46, 0xeb, 0xc4, 0x99, 0x3c, 0x87, 0x2d,
	0x99, 0x91, 0x90, 0x71, 0xe7, 0x4e, 0x03, 0x57, 0x91, 0x43, 0x73, 0x7f, 0x72, 0x02, 0xf7, 0xa3,
	0x59, 0x9a, 0x4c, 0x9f, 0xd5, 0xa3, 0xfd, 0xc9, 0x05, 0xab, 0x38, 0xa4, 0xf3, 0x21, 0xa4, 0x0e,
	0x0f, 0x62, 0xc5, 0x14, 0xb6, 0x99, 0x7f, 0xc9, 0x43, 0x3c, 0x17, 0x43, 0xd3, 0xfd, 0x36, 0x5d,
	0x84, 0xbd, 0xdf, 0x2c, 0x78, 0xd8, 0x12, 0xe1, 0xa0, 0x75, 0xc9, 0xc2, 0x21, 0xbe, 0x6f, 0xdf,
	0x8b, 0xaf, 0x5d, 0xf1, 0xff, 0xbc, 0x76, 0x07, 0xb0, 0x13, 0x49, 0x31, 0x12, 0x0a, 0xe7, 0x5f,
	0xd7, 0x05, 0xd4, 0x6b, 0x43, 0xf5, 0x15, 0x0b, 0xf2, 0x6f, 0x7b, 0x1f, 0x2a, 0x7e, 0x90, 0xe8,
	0x11, 0xe6, 0xba, 0x9a, 0x02, 0x5a, 0x3b, 0x81, 0xf0, 0x59, 0x90, 0xe9, 0x3b, 0xd5, 0xd6, 0x2c,
	0x74, 0xe8, 0xc3, 0x87, 0xff, 0xf1, 0x90, 0x91, 0x1a, 0xec, 0xaf, 0x31, 0x5f, 0x74, 0x44, 0x88,
	0x76, 0x81, 0x78, 0xe0, 0xae, 0xf3, 0xd0, 0x78, 0x34, 0xb6, 0xad, 0xc3, 0xb7, 0x0b, 0xef, 0xb2,
	0xb9, 0x7a, 0x1f, 0x9c, 0x45, 0xec, 0xa2, 0x95, 0x56, 0x6e, 0x17, 0x56, 0x5a, 0x33, 0xf1, 0xd8,
	0x16, 0xf9, 0x18, 0x9e, 0x2c, 0x5b, 0x67, 0x38, 0xb6, 0x8b, 0xe4, 0x09, 0xec, 0x2e, 0xb9, 0x4c,
	0xa6, 0x66, 0x97, 0x0e, 0x7f, 0xb1, 0x80, 0xe4, 0x76, 0x11, 0xf4, 0x51, 0x9a, 0xa2, 0x0e, 0xc0,
	0x5b, 0x46, 0x2f, 0xce, 0xc2, 0x58, 0xb1, 0x20, 0x98, 0x58, 0xec, 0xc2, 0xdc, 0x5c, 0xa6, 0x7e,
	0x2f, 0x71, 0x14, 0xbd, 0x92, 0x5c, 0xa1, 0x6d, 0xcd, 0xcd, 0x65, 0xde, 0x83, 0xa2, 0x8f, 0xfc,
	0x0a, 0xed, 0xe2, 0x49, 0xfb, 0xfa, 0x9d, 0x5b, 0xb8, 0x79, 0xe7, 0x16, 0xae, 0x6f, 0x5d, 0xeb,
	0xe6, 0xd6, 0xb5, 0xfe, 0xbc, 0x75, 0xad, 0xb7, 0x77, 0x6e, 0xe1, 0xe6, 0xce, 0x2d, 0xfc, 0x7e,
	0xe7, 0x16, 0xbe, 0xfb, 0x74, 0xc8, 0xd5, 0x65, 0xd2, 0x6b, 0xf8, 0x62, 0xd4, 0x1c, 0xb0, 0x90,
	0x25, 0xdf, 0x73, 0x6c, 0xa6, 0xba, 0x6a, 0xf2, 0x6c, 0x4d, 0x97, 0xa8, 0xd7, 0xdb, 0x34, 0xff,
	0xf7, 0x9f, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x50, 0x95, 0x91, 0xfc, 0x45, 0x08, 0x00, 0x00,
}

func (m *RaftPeerAttribute) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RaftPeerAttribute) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintBabuza(dAtA, i, uint64(m.Id))
	}
	if len(m.RaftListenAddr) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintBabuza(dAtA, i, uint64(len(m.RaftListenAddr)))
		i += copy(dAtA[i:], m.RaftListenAddr)
	}
	if m.IsLearner {
		dAtA[i] = 0x18
		i++
		if m.IsLearner {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	return i, nil
}

func (m *Peer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Peer) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintBabuza(dAtA, i, uint64(m.RaftPeerAttr.Size()))
	n1, err := m.RaftPeerAttr.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n1
	if len(m.AppServiceAddresses) > 0 {
		for _, s := range m.AppServiceAddresses {
			dAtA[i] = 0x12
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	return i, nil
}

func (m *SnapshotFileDesc) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SnapshotFileDesc) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.FileType != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintBabuza(dAtA, i, uint64(m.FileType))
	}
	if m.CompressionType != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintBabuza(dAtA, i, uint64(m.CompressionType))
	}
	if len(m.Tag) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintBabuza(dAtA, i, uint64(len(m.Tag)))
		i += copy(dAtA[i:], m.Tag)
	}
	if m.FileSize != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintBabuza(dAtA, i, uint64(m.FileSize))
	}
	if m.FileCrc64 != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintBabuza(dAtA, i, uint64(m.FileCrc64))
	}
	if len(m.Metadata) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintBabuza(dAtA, i, uint64(len(m.Metadata)))
		i += copy(dAtA[i:], m.Metadata)
	}
	return i, nil
}

func (m *SnapshotMetadata) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SnapshotMetadata) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Version != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintBabuza(dAtA, i, uint64(m.Version))
	}
	dAtA[i] = 0x12
	i++
	i = encodeVarintBabuza(dAtA, i, uint64(m.Snapshot.Size()))
	n2, err := m.Snapshot.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n2
	if len(m.Files) > 0 {
		for k, _ := range m.Files {
			dAtA[i] = 0x1a
			i++
			v := m.Files[k]
			msgSize := 0
			if (&v) != nil {
				msgSize = (&v).Size()
				msgSize += 1 + sovBabuza(uint64(msgSize))
			}
			mapSize := 1 + len(k) + sovBabuza(uint64(len(k))) + msgSize
			i = encodeVarintBabuza(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintBabuza(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			dAtA[i] = 0x12
			i++
			i = encodeVarintBabuza(dAtA, i, uint64((&v).Size()))
			n3, err := (&v).MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n3
		}
	}
	return i, nil
}

func (m *RegisterSessionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RegisterSessionRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *PubAppServiceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PubAppServiceRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.PubServicePeerID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintBabuza(dAtA, i, uint64(m.PubServicePeerID))
	}
	if len(m.AppServiceAddresses) > 0 {
		for _, s := range m.AppServiceAddresses {
			dAtA[i] = 0x1a
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	return i, nil
}

func (m *RequestContext) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RequestContext) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ReplyID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintBabuza(dAtA, i, uint64(m.ReplyID))
	}
	if m.SessionID != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintBabuza(dAtA, i, uint64(m.SessionID))
	}
	if m.SequenceNum != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintBabuza(dAtA, i, uint64(m.SequenceNum))
	}
	if m.LowestSeqNumNotYetReplied != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintBabuza(dAtA, i, uint64(m.LowestSeqNumNotYetReplied))
	}
	return i, nil
}

func (m *NormalRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NormalRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintBabuza(dAtA, i, uint64(m.Context.Size()))
	n4, err := m.Context.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n4
	if m.Register != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintBabuza(dAtA, i, uint64(m.Register.Size()))
		n5, err := m.Register.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n5
	}
	if m.PubAppService != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintBabuza(dAtA, i, uint64(m.PubAppService.Size()))
		n6, err := m.PubAppService.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n6
	}
	if len(m.StateMachineLog) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintBabuza(dAtA, i, uint64(len(m.StateMachineLog)))
		i += copy(dAtA[i:], m.StateMachineLog)
	}
	return i, nil
}

func (m *ConfChangeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConfChangeRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintBabuza(dAtA, i, uint64(m.Context.Size()))
	n7, err := m.Context.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n7
	dAtA[i] = 0x12
	i++
	i = encodeVarintBabuza(dAtA, i, uint64(m.RaftPeerAttr.Size()))
	n8, err := m.RaftPeerAttr.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n8
	if m.PromoteLearner {
		dAtA[i] = 0x18
		i++
		if m.PromoteLearner {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	return i, nil
}

func (m *WalMetadata) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WalMetadata) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ClusterID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintBabuza(dAtA, i, uint64(m.ClusterID))
	}
	if m.LocalPeerID != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintBabuza(dAtA, i, uint64(m.LocalPeerID))
	}
	return i, nil
}

func encodeVarintBabuza(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *RaftPeerAttribute) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovBabuza(uint64(m.Id))
	}
	l = len(m.RaftListenAddr)
	if l > 0 {
		n += 1 + l + sovBabuza(uint64(l))
	}
	if m.IsLearner {
		n += 2
	}
	return n
}

func (m *Peer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.RaftPeerAttr.Size()
	n += 1 + l + sovBabuza(uint64(l))
	if len(m.AppServiceAddresses) > 0 {
		for _, s := range m.AppServiceAddresses {
			l = len(s)
			n += 1 + l + sovBabuza(uint64(l))
		}
	}
	return n
}

func (m *SnapshotFileDesc) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FileType != 0 {
		n += 1 + sovBabuza(uint64(m.FileType))
	}
	if m.CompressionType != 0 {
		n += 1 + sovBabuza(uint64(m.CompressionType))
	}
	l = len(m.Tag)
	if l > 0 {
		n += 1 + l + sovBabuza(uint64(l))
	}
	if m.FileSize != 0 {
		n += 1 + sovBabuza(uint64(m.FileSize))
	}
	if m.FileCrc64 != 0 {
		n += 1 + sovBabuza(uint64(m.FileCrc64))
	}
	l = len(m.Metadata)
	if l > 0 {
		n += 1 + l + sovBabuza(uint64(l))
	}
	return n
}

func (m *SnapshotMetadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Version != 0 {
		n += 1 + sovBabuza(uint64(m.Version))
	}
	l = m.Snapshot.Size()
	n += 1 + l + sovBabuza(uint64(l))
	if len(m.Files) > 0 {
		for k, v := range m.Files {
			_ = k
			_ = v
			l = v.Size()
			mapEntrySize := 1 + len(k) + sovBabuza(uint64(len(k))) + 1 + l + sovBabuza(uint64(l))
			n += mapEntrySize + 1 + sovBabuza(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *RegisterSessionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *PubAppServiceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PubServicePeerID != 0 {
		n += 1 + sovBabuza(uint64(m.PubServicePeerID))
	}
	if len(m.AppServiceAddresses) > 0 {
		for _, s := range m.AppServiceAddresses {
			l = len(s)
			n += 1 + l + sovBabuza(uint64(l))
		}
	}
	return n
}

func (m *RequestContext) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ReplyID != 0 {
		n += 1 + sovBabuza(uint64(m.ReplyID))
	}
	if m.SessionID != 0 {
		n += 1 + sovBabuza(uint64(m.SessionID))
	}
	if m.SequenceNum != 0 {
		n += 1 + sovBabuza(uint64(m.SequenceNum))
	}
	if m.LowestSeqNumNotYetReplied != 0 {
		n += 1 + sovBabuza(uint64(m.LowestSeqNumNotYetReplied))
	}
	return n
}

func (m *NormalRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Context.Size()
	n += 1 + l + sovBabuza(uint64(l))
	if m.Register != nil {
		l = m.Register.Size()
		n += 1 + l + sovBabuza(uint64(l))
	}
	if m.PubAppService != nil {
		l = m.PubAppService.Size()
		n += 1 + l + sovBabuza(uint64(l))
	}
	l = len(m.StateMachineLog)
	if l > 0 {
		n += 1 + l + sovBabuza(uint64(l))
	}
	return n
}

func (m *ConfChangeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Context.Size()
	n += 1 + l + sovBabuza(uint64(l))
	l = m.RaftPeerAttr.Size()
	n += 1 + l + sovBabuza(uint64(l))
	if m.PromoteLearner {
		n += 2
	}
	return n
}

func (m *WalMetadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ClusterID != 0 {
		n += 1 + sovBabuza(uint64(m.ClusterID))
	}
	if m.LocalPeerID != 0 {
		n += 1 + sovBabuza(uint64(m.LocalPeerID))
	}
	return n
}

func sovBabuza(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozBabuza(x uint64) (n int) {
	return sovBabuza(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RaftPeerAttribute) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBabuza
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RaftPeerAttribute: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RaftPeerAttribute: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabuza
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RaftListenAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabuza
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBabuza
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBabuza
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RaftListenAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsLearner", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabuza
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsLearner = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipBabuza(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBabuza
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBabuza
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Peer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBabuza
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Peer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Peer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RaftPeerAttr", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabuza
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBabuza
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBabuza
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RaftPeerAttr.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppServiceAddresses", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabuza
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBabuza
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBabuza
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AppServiceAddresses = append(m.AppServiceAddresses, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBabuza(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBabuza
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBabuza
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SnapshotFileDesc) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBabuza
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SnapshotFileDesc: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SnapshotFileDesc: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileType", wireType)
			}
			m.FileType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabuza
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FileType |= SnapshotFileType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompressionType", wireType)
			}
			m.CompressionType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabuza
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CompressionType |= SnapshotFileCompressionType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tag", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabuza
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBabuza
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBabuza
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tag = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileSize", wireType)
			}
			m.FileSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabuza
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FileSize |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileCrc64", wireType)
			}
			m.FileCrc64 = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabuza
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FileCrc64 |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabuza
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBabuza
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBabuza
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Metadata = append(m.Metadata[:0], dAtA[iNdEx:postIndex]...)
			if m.Metadata == nil {
				m.Metadata = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBabuza(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBabuza
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBabuza
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SnapshotMetadata) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBabuza
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SnapshotMetadata: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SnapshotMetadata: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabuza
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Version |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Snapshot", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabuza
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBabuza
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBabuza
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Snapshot.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Files", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabuza
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBabuza
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBabuza
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Files == nil {
				m.Files = make(map[string]SnapshotFileDesc)
			}
			var mapkey string
			mapvalue := &SnapshotFileDesc{}
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowBabuza
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowBabuza
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthBabuza
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthBabuza
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowBabuza
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthBabuza
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthBabuza
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &SnapshotFileDesc{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipBabuza(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthBabuza
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Files[mapkey] = *mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBabuza(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBabuza
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBabuza
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RegisterSessionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBabuza
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RegisterSessionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RegisterSessionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipBabuza(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBabuza
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBabuza
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PubAppServiceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBabuza
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PubAppServiceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PubAppServiceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubServicePeerID", wireType)
			}
			m.PubServicePeerID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabuza
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PubServicePeerID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppServiceAddresses", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabuza
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBabuza
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBabuza
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AppServiceAddresses = append(m.AppServiceAddresses, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBabuza(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBabuza
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBabuza
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RequestContext) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBabuza
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RequestContext: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RequestContext: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReplyID", wireType)
			}
			m.ReplyID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabuza
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReplyID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionID", wireType)
			}
			m.SessionID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabuza
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SessionID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SequenceNum", wireType)
			}
			m.SequenceNum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabuza
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SequenceNum |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LowestSeqNumNotYetReplied", wireType)
			}
			m.LowestSeqNumNotYetReplied = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabuza
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LowestSeqNumNotYetReplied |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBabuza(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBabuza
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBabuza
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NormalRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBabuza
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NormalRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NormalRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Context", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabuza
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBabuza
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBabuza
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Context.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Register", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabuza
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBabuza
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBabuza
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Register == nil {
				m.Register = &RegisterSessionRequest{}
			}
			if err := m.Register.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubAppService", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabuza
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBabuza
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBabuza
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PubAppService == nil {
				m.PubAppService = &PubAppServiceRequest{}
			}
			if err := m.PubAppService.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateMachineLog", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabuza
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBabuza
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBabuza
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StateMachineLog = append(m.StateMachineLog[:0], dAtA[iNdEx:postIndex]...)
			if m.StateMachineLog == nil {
				m.StateMachineLog = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBabuza(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBabuza
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBabuza
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConfChangeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBabuza
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConfChangeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConfChangeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Context", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabuza
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBabuza
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBabuza
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Context.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RaftPeerAttr", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabuza
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBabuza
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBabuza
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RaftPeerAttr.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PromoteLearner", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabuza
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.PromoteLearner = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipBabuza(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBabuza
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBabuza
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WalMetadata) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBabuza
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WalMetadata: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WalMetadata: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClusterID", wireType)
			}
			m.ClusterID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabuza
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClusterID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LocalPeerID", wireType)
			}
			m.LocalPeerID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabuza
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LocalPeerID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBabuza(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBabuza
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBabuza
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBabuza(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBabuza
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBabuza
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBabuza
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBabuza
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthBabuza
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowBabuza
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipBabuza(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthBabuza
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthBabuza = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBabuza   = fmt.Errorf("proto: integer overflow")
)
