syntax = "proto3";
package raft;
option go_package = "github.com/fanaujie/babuza/ibabuza/babuzapb";

import "gogoproto/gogo.proto";
import "go.etcd.io/etcd/raft/raftpb/raft.proto";
import "babuza.proto";

option (gogoproto.marshaler_all) = true;
option (gogoproto.sizer_all) = true;
option (gogoproto.unmarshaler_all) = true;
option (gogoproto.goproto_getters_all) = false;
option (gogoproto.goproto_enum_prefix_all) = false;
option (gogoproto.goproto_unkeyed_all) = false;
option (gogoproto.goproto_unrecognized_all) = false;
option (gogoproto.goproto_sizecache_all) = false;


message BatchMessage {
  uint64  clusterID = 1;
  uint64  groupID = 2;
  repeated raftpb.Message  messages = 3 [(gogoproto.nullable) = false];
}

message SnapshotChunkMessage {
  babuza.SnapshotFileType  fileType  = 1;
  string                    fileTag  = 2;
  int64                          id  = 3;
  bytes                        data  = 4;
  uint32               continueCrc32  = 5;
  bool                    lastChunk  = 6;
}

message SnapshotMessage {
  uint64    clusterID     = 1;
  uint64    groupID       = 2;
  uint64    from          = 4;
  uint64    to            = 5;
  uint64    term          = 6;
  uint64    index         = 7;
  babuza.SnapshotMetadata metadata      = 8 [(gogoproto.nullable) = false];
  SnapshotChunkMessage    chunkMessage  = 9 [(gogoproto.nullable) = false];
  raftpb.Message          finishMessage = 10 [(gogoproto.nullable) = false];
}

enum RpcStatus {
  SUCCESS = 0;
  FAILED = 1;
}


message GetClusterPeersRequest {
  uint64  clusterID = 1;
  uint64  groupID   = 2;
  uint64  from      = 3;
  uint64  to        = 4;
}

message GetClusterPeersResponse {
  RpcStatus status = 1;
  string   message = 2;
  repeated babuza.Peer  Peers = 3[(gogoproto.nullable) = false];
}

message PublishApplicationServiceRequest {
  uint64  clusterID        = 1;
  uint64  groupID          = 2;
  uint64  from             = 3;
  uint64  to               = 4;
  uint64  proposalReplyID  = 5;
  repeated string appServiceAddresses  = 6;
}

message PublishApplicationServiceResponse {
  RpcStatus status = 1;
  string   message = 2;
}


message MultiRaftMessage {
  uint64  clusterID = 1;
  uint64  groupID = 2;
  raftpb.Message  message = 3 [(gogoproto.nullable) = false];
}