syntax = "proto3";
package raft;
option go_package = "github.com/fanaujie/babuza/ibabuza/babuzapb";

import "gogoproto/gogo.proto";
import "go.etcd.io/etcd/raft/raftpb/raft.proto";
import "babuza.proto";

option (gogoproto.marshaler_all) = true;
option (gogoproto.sizer_all) = true;
option (gogoproto.unmarshaler_all) = true;
option (gogoproto.goproto_getters_all) = false;
option (gogoproto.goproto_enum_prefix_all) = false;
option (gogoproto.goproto_unkeyed_all) = false;
option (gogoproto.goproto_unrecognized_all) = false;
option (gogoproto.goproto_sizecache_all) = false;


message BatchMessage {
  repeated raftpb.Message  messages = 1 [(gogoproto.nullable) = false];
}

message SnapshotChunkMessage {
  babuza.SnapshotFileType  fileType  = 1;
  string                    fileTag  = 2;
  int64                          id  = 3;
  bytes                        data  = 4;
  uint32               continueCrc32  = 5;
  bool                    lastChunk  = 6;
}

message SnapshotMessage {
  uint64    from          = 1;
  uint64    to            = 2;
  uint64    term          = 3;
  uint64    index         = 4;
  babuza.SnapshotMetadata metadata      = 5;
  SnapshotChunkMessage    chunkMessage  = 6;
  raftpb.Message          finishMessage = 7;
}

enum RpcStatus {
  SUCCESS = 0;
  FAILED = 1;
}


message GetClusterPeersRequest {
  uint64  clusterId = 1;
  uint64  fromId      = 2;
  uint64  toId        = 3;
}

message GetClusterPeersResponse {
  RpcStatus status = 1;
  string   message = 2;
  repeated babuza.Peer  Peers = 3[(gogoproto.nullable) = false];
}

message PublishApplicationServiceRequest {
  uint64  clusterId        = 1;
  uint64  fromId           = 2;
  uint64  toId             = 3;
  uint64  proposalReplyId  = 4;
  repeated string appServiceAddresses  = 5;
}

message PublishApplicationServiceResponse {
  RpcStatus status = 1;
  string   message = 2;
}