// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: wal.proto

package pb

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type LogType int32

const (
	LogTypeNormalEntry       LogType = 0
	LogTypeConfChangeEntry   LogType = 1
	LogTypeConfChangeV2Entry LogType = 2
	LogTypeCrc               LogType = 26
	LogTypeMetadata          LogType = 27
	LogTypeHardState         LogType = 28
	LogTypeSnapshot          LogType = 29
	LogTypeNextEntry         LogType = 30
	LogTypeMax               LogType = 31
)

var LogType_name = map[int32]string{
	0:  "LogTypeNormalEntry",
	1:  "LogTypeConfChangeEntry",
	2:  "LogTypeConfChangeV2Entry",
	26: "LogTypeCrc",
	27: "LogTypeMetadata",
	28: "LogTypeHardState",
	29: "LogTypeSnapshot",
	30: "LogTypeNextEntry",
	31: "LogTypeMax",
}

var LogType_value = map[string]int32{
	"LogTypeNormalEntry":       0,
	"LogTypeConfChangeEntry":   1,
	"LogTypeConfChangeV2Entry": 2,
	"LogTypeCrc":               26,
	"LogTypeMetadata":          27,
	"LogTypeHardState":         28,
	"LogTypeSnapshot":          29,
	"LogTypeNextEntry":         30,
	"LogTypeMax":               31,
}

func (x LogType) String() string {
	return proto.EnumName(LogType_name, int32(x))
}

func (LogType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ae6364fc8077884f, []int{0}
}

type WalNextEntry struct {
	NextTerm  uint64 `protobuf:"varint,1,opt,name=nextTerm,proto3" json:"nextTerm,omitempty"`
	NextIndex uint64 `protobuf:"varint,2,opt,name=nextIndex,proto3" json:"nextIndex,omitempty"`
}

func (m *WalNextEntry) Reset()         { *m = WalNextEntry{} }
func (m *WalNextEntry) String() string { return proto.CompactTextString(m) }
func (*WalNextEntry) ProtoMessage()    {}
func (*WalNextEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6364fc8077884f, []int{0}
}
func (m *WalNextEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WalNextEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WalNextEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WalNextEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalNextEntry.Merge(m, src)
}
func (m *WalNextEntry) XXX_Size() int {
	return m.Size()
}
func (m *WalNextEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_WalNextEntry.DiscardUnknown(m)
}

var xxx_messageInfo_WalNextEntry proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("babuza.LogType", LogType_name, LogType_value)
	proto.RegisterType((*WalNextEntry)(nil), "babuza.WalNextEntry")
}

func init() { proto.RegisterFile("wal.proto", fileDescriptor_ae6364fc8077884f) }

var fileDescriptor_ae6364fc8077884f = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xd1, 0x4a, 0x32, 0x41,
	0x14, 0xc7, 0x67, 0xe4, 0xc3, 0x2f, 0x0f, 0x51, 0xc3, 0x24, 0x22, 0x9b, 0x4d, 0xd1, 0x55, 0x14,
	0xb8, 0x50, 0x6f, 0x90, 0x04, 0x06, 0xe9, 0x45, 0x4a, 0x41, 0x77, 0x67, 0x75, 0x1c, 0xad, 0x75,
	0x66, 0x99, 0x46, 0x5c, 0x7b, 0x8a, 0x1e, 0xcb, 0x4b, 0xbb, 0xeb, 0x32, 0xf5, 0x45, 0xc2, 0xdd,
	0xcd, 0x16, 0xba, 0xfb, 0x9f, 0xdf, 0xef, 0x30, 0xc3, 0xf9, 0x43, 0x69, 0x8a, 0x61, 0x3d, 0xb2,
	0xc6, 0x19, 0x5e, 0x0c, 0x30, 0x98, 0xbc, 0xa1, 0x57, 0x56, 0x46, 0x99, 0x04, 0xf9, 0x9b, 0x94,
	0xda, 0xd3, 0x26, 0xec, 0x3e, 0x62, 0xd8, 0x96, 0xb1, 0xbb, 0xd1, 0xce, 0xce, 0xb8, 0x07, 0x3b,
	0x5a, 0xc6, 0xae, 0x2b, 0xed, 0xb8, 0x4a, 0x4f, 0xe8, 0xd9, 0xbf, 0xfb, 0xed, 0xcc, 0x6b, 0x50,
	0xda, 0xe4, 0x5b, 0xdd, 0x97, 0x71, 0xb5, 0x90, 0xc8, 0x5f, 0x70, 0xfe, 0x41, 0xe1, 0xff, 0x9d,
	0x51, 0xdd, 0x59, 0x24, 0x79, 0x05, 0x78, 0x16, 0xdb, 0xc6, 0x8e, 0x31, 0x4c, 0xde, 0x66, 0x84,
	0x7b, 0x50, 0xc9, 0x78, 0xc3, 0xe8, 0x41, 0x63, 0x88, 0x5a, 0xc9, 0xd4, 0x51, 0x5e, 0x83, 0xea,
	0x1f, 0xf7, 0x70, 0x99, 0xda, 0x02, 0xdf, 0x03, 0xf8, 0xb1, 0xb6, 0xc7, 0x3c, 0x7e, 0x00, 0xfb,
	0xd9, 0xdc, 0x92, 0x0e, 0xfb, 0xe8, 0x90, 0x1d, 0xf2, 0x32, 0xb0, 0x0c, 0x36, 0xd1, 0xf6, 0x3b,
	0x0e, 0x9d, 0x64, 0xb5, 0xdc, 0x6a, 0x47, 0x63, 0xf4, 0x3a, 0x34, 0x8e, 0x1d, 0xe5, 0x56, 0xb7,
	0xb7, 0x33, 0x91, 0xfb, 0xa5, 0x85, 0x31, 0x3b, 0xbe, 0x6e, 0xcd, 0x97, 0x82, 0x2c, 0x96, 0x82,
	0xcc, 0x57, 0x82, 0x2e, 0x56, 0x82, 0x7e, 0xad, 0x04, 0x7d, 0x5f, 0x0b, 0xb2, 0x58, 0x0b, 0xf2,
	0xb9, 0x16, 0xe4, 0xe9, 0x42, 0x8d, 0xdc, 0x70, 0x12, 0xd4, 0x7b, 0x66, 0xec, 0x0f, 0x50, 0xe3,
	0xe4, 0x79, 0x24, 0xfd, 0xb4, 0x71, 0x3f, 0x7a, 0x51, 0x59, 0x9c, 0x62, 0xe8, 0x47, 0x41, 0x50,
	0x4c, 0x3a, 0xbf, 0xfa, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xa6, 0x25, 0x85, 0x29, 0x9e, 0x01, 0x00,
	0x00,
}

func (m *WalNextEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WalNextEntry) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.NextTerm != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintWal(dAtA, i, uint64(m.NextTerm))
	}
	if m.NextIndex != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintWal(dAtA, i, uint64(m.NextIndex))
	}
	return i, nil
}

func encodeVarintWal(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *WalNextEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NextTerm != 0 {
		n += 1 + sovWal(uint64(m.NextTerm))
	}
	if m.NextIndex != 0 {
		n += 1 + sovWal(uint64(m.NextIndex))
	}
	return n
}

func sovWal(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozWal(x uint64) (n int) {
	return sovWal(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *WalNextEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWal
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WalNextEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WalNextEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextTerm", wireType)
			}
			m.NextTerm = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextTerm |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextIndex", wireType)
			}
			m.NextIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipWal(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWal
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthWal
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipWal(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowWal
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWal
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWal
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthWal
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthWal
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowWal
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipWal(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthWal
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthWal = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowWal   = fmt.Errorf("proto: integer overflow")
)
