// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pd.proto

package pb

import (
	context "context"
	fmt "fmt"
	babuzapb "github.com/fanaujie/babuza/ibabuza/babuzapb"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	io "io"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type StoreHeartbeatReq struct {
	ClusterID   uint64 `protobuf:"varint,1,opt,name=clusterID,proto3" json:"clusterID,omitempty"`
	StoreID     uint64 `protobuf:"varint,2,opt,name=storeID,proto3" json:"storeID,omitempty"`
	LeaderCount uint64 `protobuf:"varint,3,opt,name=leaderCount,proto3" json:"leaderCount,omitempty"`
}

func (m *StoreHeartbeatReq) Reset()         { *m = StoreHeartbeatReq{} }
func (m *StoreHeartbeatReq) String() string { return proto.CompactTextString(m) }
func (*StoreHeartbeatReq) ProtoMessage()    {}
func (*StoreHeartbeatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ece4d612d87e090, []int{0}
}
func (m *StoreHeartbeatReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StoreHeartbeatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StoreHeartbeatReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StoreHeartbeatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreHeartbeatReq.Merge(m, src)
}
func (m *StoreHeartbeatReq) XXX_Size() int {
	return m.Size()
}
func (m *StoreHeartbeatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreHeartbeatReq.DiscardUnknown(m)
}

var xxx_messageInfo_StoreHeartbeatReq proto.InternalMessageInfo

type StoreHeartbeatResp struct {
	ClusterID uint64 `protobuf:"varint,1,opt,name=clusterID,proto3" json:"clusterID,omitempty"`
}

func (m *StoreHeartbeatResp) Reset()         { *m = StoreHeartbeatResp{} }
func (m *StoreHeartbeatResp) String() string { return proto.CompactTextString(m) }
func (*StoreHeartbeatResp) ProtoMessage()    {}
func (*StoreHeartbeatResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ece4d612d87e090, []int{1}
}
func (m *StoreHeartbeatResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StoreHeartbeatResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StoreHeartbeatResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StoreHeartbeatResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreHeartbeatResp.Merge(m, src)
}
func (m *StoreHeartbeatResp) XXX_Size() int {
	return m.Size()
}
func (m *StoreHeartbeatResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreHeartbeatResp.DiscardUnknown(m)
}

var xxx_messageInfo_StoreHeartbeatResp proto.InternalMessageInfo

type RaftGroupLeaderHeartbeatReq struct {
	StoreID  uint64                       `protobuf:"varint,1,opt,name=storeID,proto3" json:"storeID,omitempty"`
	GroupID  uint64                       `protobuf:"varint,2,opt,name=groupID,proto3" json:"groupID,omitempty"`
	LeaderID uint64                       `protobuf:"varint,3,opt,name=leaderID,proto3" json:"leaderID,omitempty"`
	Peers    []babuzapb.RaftPeerAttribute `protobuf:"bytes,4,rep,name=peers,proto3" json:"peers"`
}

func (m *RaftGroupLeaderHeartbeatReq) Reset()         { *m = RaftGroupLeaderHeartbeatReq{} }
func (m *RaftGroupLeaderHeartbeatReq) String() string { return proto.CompactTextString(m) }
func (*RaftGroupLeaderHeartbeatReq) ProtoMessage()    {}
func (*RaftGroupLeaderHeartbeatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ece4d612d87e090, []int{2}
}
func (m *RaftGroupLeaderHeartbeatReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RaftGroupLeaderHeartbeatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RaftGroupLeaderHeartbeatReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RaftGroupLeaderHeartbeatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RaftGroupLeaderHeartbeatReq.Merge(m, src)
}
func (m *RaftGroupLeaderHeartbeatReq) XXX_Size() int {
	return m.Size()
}
func (m *RaftGroupLeaderHeartbeatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RaftGroupLeaderHeartbeatReq.DiscardUnknown(m)
}

var xxx_messageInfo_RaftGroupLeaderHeartbeatReq proto.InternalMessageInfo

type TransferLeader struct {
	NewLeaderID uint64 `protobuf:"varint,1,opt,name=newLeaderID,proto3" json:"newLeaderID,omitempty"`
}

func (m *TransferLeader) Reset()         { *m = TransferLeader{} }
func (m *TransferLeader) String() string { return proto.CompactTextString(m) }
func (*TransferLeader) ProtoMessage()    {}
func (*TransferLeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ece4d612d87e090, []int{3}
}
func (m *TransferLeader) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TransferLeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TransferLeader.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TransferLeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferLeader.Merge(m, src)
}
func (m *TransferLeader) XXX_Size() int {
	return m.Size()
}
func (m *TransferLeader) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferLeader.DiscardUnknown(m)
}

var xxx_messageInfo_TransferLeader proto.InternalMessageInfo

type RaftGroupLeaderHeartbeatResp struct {
	TransferLeader *TransferLeader `protobuf:"bytes,1,opt,name=transferLeader,proto3" json:"transferLeader,omitempty"`
}

func (m *RaftGroupLeaderHeartbeatResp) Reset()         { *m = RaftGroupLeaderHeartbeatResp{} }
func (m *RaftGroupLeaderHeartbeatResp) String() string { return proto.CompactTextString(m) }
func (*RaftGroupLeaderHeartbeatResp) ProtoMessage()    {}
func (*RaftGroupLeaderHeartbeatResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ece4d612d87e090, []int{4}
}
func (m *RaftGroupLeaderHeartbeatResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RaftGroupLeaderHeartbeatResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RaftGroupLeaderHeartbeatResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RaftGroupLeaderHeartbeatResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RaftGroupLeaderHeartbeatResp.Merge(m, src)
}
func (m *RaftGroupLeaderHeartbeatResp) XXX_Size() int {
	return m.Size()
}
func (m *RaftGroupLeaderHeartbeatResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RaftGroupLeaderHeartbeatResp.DiscardUnknown(m)
}

var xxx_messageInfo_RaftGroupLeaderHeartbeatResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*StoreHeartbeatReq)(nil), "pdpb.StoreHeartbeatReq")
	proto.RegisterType((*StoreHeartbeatResp)(nil), "pdpb.StoreHeartbeatResp")
	proto.RegisterType((*RaftGroupLeaderHeartbeatReq)(nil), "pdpb.RaftGroupLeaderHeartbeatReq")
	proto.RegisterType((*TransferLeader)(nil), "pdpb.TransferLeader")
	proto.RegisterType((*RaftGroupLeaderHeartbeatResp)(nil), "pdpb.RaftGroupLeaderHeartbeatResp")
}

func init() { proto.RegisterFile("pd.proto", fileDescriptor_3ece4d612d87e090) }

var fileDescriptor_3ece4d612d87e090 = []byte{
	// 433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4f, 0x6e, 0xd3, 0x40,
	0x14, 0xc6, 0x3d, 0x34, 0xd0, 0xf6, 0x05, 0x45, 0x62, 0x54, 0x89, 0xc1, 0x54, 0x43, 0xf0, 0xaa,
	0x1b, 0x6c, 0xc9, 0x08, 0x89, 0x05, 0x1b, 0x4a, 0x10, 0x44, 0xea, 0xa2, 0x72, 0x59, 0x55, 0x6c,
	0x66, 0x92, 0x17, 0x63, 0x48, 0x32, 0xc3, 0xcc, 0x18, 0x10, 0xa7, 0xe0, 0x10, 0xdc, 0x81, 0x2b,
	0x64, 0x99, 0x25, 0x2b, 0x44, 0x93, 0x8b, 0x20, 0x7b, 0x52, 0x1a, 0x17, 0x9a, 0xee, 0xfc, 0xfe,
	0x7e, 0x3f, 0xbf, 0x6f, 0x60, 0x47, 0x0f, 0x63, 0x6d, 0x94, 0x53, 0xb4, 0xa5, 0x87, 0x5a, 0x86,
	0x7b, 0xb9, 0xca, 0x55, 0x9d, 0x48, 0xaa, 0x2f, 0x5f, 0x0b, 0x6f, 0x4b, 0x21, 0xcb, 0xaf, 0xc2,
	0x47, 0xd1, 0x04, 0xee, 0x9c, 0x38, 0x65, 0xf0, 0x35, 0x0a, 0xe3, 0x24, 0x0a, 0x97, 0xe1, 0x47,
	0xba, 0x0f, 0xbb, 0x83, 0x71, 0x69, 0x1d, 0x9a, 0x7e, 0x8f, 0x91, 0x2e, 0x39, 0x68, 0x65, 0x17,
	0x09, 0xca, 0x60, 0xdb, 0x56, 0x23, 0xfd, 0x1e, 0xbb, 0x51, 0xd7, 0xce, 0x43, 0xda, 0x85, 0xf6,
	0x18, 0xc5, 0x10, 0xcd, 0x0b, 0x55, 0x4e, 0x1d, 0xdb, 0xaa, 0xab, 0xeb, 0xa9, 0x28, 0x05, 0x7a,
	0x59, 0xce, 0xea, 0xcd, 0x7a, 0xd1, 0x77, 0x02, 0xf7, 0x33, 0x31, 0x72, 0xaf, 0x8c, 0x2a, 0xf5,
	0x51, 0xbd, 0xac, 0x41, 0xbb, 0xc6, 0x43, 0x9a, 0x3c, 0x0c, 0xb6, 0xf3, 0x6a, 0xe8, 0x82, 0x74,
	0x15, 0xd2, 0x10, 0x76, 0x3c, 0x56, 0xbf, 0xb7, 0xc2, 0xfc, 0x1b, 0xd3, 0x27, 0x70, 0x53, 0x23,
	0x1a, 0xcb, 0x5a, 0xdd, 0xad, 0x83, 0x76, 0x7a, 0x2f, 0x5e, 0x1d, 0xac, 0x62, 0x38, 0x46, 0x34,
	0xcf, 0x9d, 0x33, 0x85, 0x2c, 0x1d, 0x1e, 0xb6, 0x66, 0xbf, 0x1e, 0x04, 0x99, 0xef, 0x8e, 0x52,
	0xe8, 0xbc, 0x31, 0x62, 0x6a, 0x47, 0x68, 0x3c, 0x64, 0x75, 0x8e, 0x29, 0x7e, 0x3e, 0x3a, 0xd7,
	0xf1, 0x70, 0xeb, 0xa9, 0xe8, 0x2d, 0xec, 0x5f, 0xfd, 0x67, 0x56, 0xd3, 0x67, 0xd0, 0x71, 0x8d,
	0x9d, 0xf5, 0x92, 0x76, 0xba, 0x17, 0x57, 0x06, 0xc7, 0x4d, 0xbd, 0xec, 0x52, 0x6f, 0xfa, 0x83,
	0xc0, 0xee, 0x71, 0xef, 0x04, 0xcd, 0xa7, 0x62, 0x80, 0xf4, 0x25, 0x74, 0x9a, 0xa7, 0xa7, 0x77,
	0xfd, 0x96, 0x7f, 0xfc, 0x0f, 0xd9, 0xff, 0x0b, 0x56, 0x47, 0x01, 0x1d, 0x00, 0xbb, 0x0a, 0x99,
	0x3e, 0xf4, 0x73, 0x1b, 0xcc, 0x0a, 0xa3, 0xeb, 0x5a, 0x2a, 0x91, 0xc3, 0xd3, 0xd9, 0x19, 0x0f,
	0xe6, 0x67, 0x3c, 0x98, 0x2d, 0x38, 0x99, 0x2f, 0x38, 0xf9, 0xbd, 0xe0, 0xe4, 0xdb, 0x92, 0x07,
	0xf3, 0x25, 0x0f, 0x7e, 0x2e, 0x79, 0x70, 0xfa, 0x34, 0x2f, 0xdc, 0xbb, 0x52, 0xc6, 0x03, 0x35,
	0x49, 0x46, 0x62, 0x2a, 0xca, 0xf7, 0x05, 0x26, 0xde, 0xa8, 0x04, 0xbf, 0x88, 0x89, 0x1e, 0xa3,
	0x4d, 0x0c, 0x0e, 0x0b, 0xfb, 0x68, 0xf5, 0x92, 0x12, 0xfd, 0x21, 0x4f, 0xb4, 0x94, 0xb7, 0xea,
	0x87, 0xff, 0xf8, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x77, 0x5d, 0x6b, 0x9e, 0x2e, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PDServiceClient is the client API for PDService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PDServiceClient interface {
	StoreHeartbeat(ctx context.Context, in *StoreHeartbeatReq, opts ...grpc.CallOption) (*StoreHeartbeatResp, error)
	RaftGroupLeaderHeartbeat(ctx context.Context, in *RaftGroupLeaderHeartbeatReq, opts ...grpc.CallOption) (*RaftGroupLeaderHeartbeatResp, error)
}

type pDServiceClient struct {
	cc *grpc.ClientConn
}

func NewPDServiceClient(cc *grpc.ClientConn) PDServiceClient {
	return &pDServiceClient{cc}
}

func (c *pDServiceClient) StoreHeartbeat(ctx context.Context, in *StoreHeartbeatReq, opts ...grpc.CallOption) (*StoreHeartbeatResp, error) {
	out := new(StoreHeartbeatResp)
	err := c.cc.Invoke(ctx, "/pdpb.PDService/StoreHeartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pDServiceClient) RaftGroupLeaderHeartbeat(ctx context.Context, in *RaftGroupLeaderHeartbeatReq, opts ...grpc.CallOption) (*RaftGroupLeaderHeartbeatResp, error) {
	out := new(RaftGroupLeaderHeartbeatResp)
	err := c.cc.Invoke(ctx, "/pdpb.PDService/RaftGroupLeaderHeartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PDServiceServer is the server API for PDService service.
type PDServiceServer interface {
	StoreHeartbeat(context.Context, *StoreHeartbeatReq) (*StoreHeartbeatResp, error)
	RaftGroupLeaderHeartbeat(context.Context, *RaftGroupLeaderHeartbeatReq) (*RaftGroupLeaderHeartbeatResp, error)
}

func RegisterPDServiceServer(s *grpc.Server, srv PDServiceServer) {
	s.RegisterService(&_PDService_serviceDesc, srv)
}

func _PDService_StoreHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreHeartbeatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PDServiceServer).StoreHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pdpb.PDService/StoreHeartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PDServiceServer).StoreHeartbeat(ctx, req.(*StoreHeartbeatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PDService_RaftGroupLeaderHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RaftGroupLeaderHeartbeatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PDServiceServer).RaftGroupLeaderHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pdpb.PDService/RaftGroupLeaderHeartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PDServiceServer).RaftGroupLeaderHeartbeat(ctx, req.(*RaftGroupLeaderHeartbeatReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _PDService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pdpb.PDService",
	HandlerType: (*PDServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreHeartbeat",
			Handler:    _PDService_StoreHeartbeat_Handler,
		},
		{
			MethodName: "RaftGroupLeaderHeartbeat",
			Handler:    _PDService_RaftGroupLeaderHeartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pd.proto",
}

func (m *StoreHeartbeatReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StoreHeartbeatReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ClusterID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintPd(dAtA, i, uint64(m.ClusterID))
	}
	if m.StoreID != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintPd(dAtA, i, uint64(m.StoreID))
	}
	if m.LeaderCount != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintPd(dAtA, i, uint64(m.LeaderCount))
	}
	return i, nil
}

func (m *StoreHeartbeatResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StoreHeartbeatResp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ClusterID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintPd(dAtA, i, uint64(m.ClusterID))
	}
	return i, nil
}

func (m *RaftGroupLeaderHeartbeatReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RaftGroupLeaderHeartbeatReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.StoreID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintPd(dAtA, i, uint64(m.StoreID))
	}
	if m.GroupID != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintPd(dAtA, i, uint64(m.GroupID))
	}
	if m.LeaderID != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintPd(dAtA, i, uint64(m.LeaderID))
	}
	if len(m.Peers) > 0 {
		for _, msg := range m.Peers {
			dAtA[i] = 0x22
			i++
			i = encodeVarintPd(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *TransferLeader) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TransferLeader) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.NewLeaderID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintPd(dAtA, i, uint64(m.NewLeaderID))
	}
	return i, nil
}

func (m *RaftGroupLeaderHeartbeatResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RaftGroupLeaderHeartbeatResp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.TransferLeader != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintPd(dAtA, i, uint64(m.TransferLeader.Size()))
		n1, err := m.TransferLeader.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	return i, nil
}

func encodeVarintPd(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *StoreHeartbeatReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ClusterID != 0 {
		n += 1 + sovPd(uint64(m.ClusterID))
	}
	if m.StoreID != 0 {
		n += 1 + sovPd(uint64(m.StoreID))
	}
	if m.LeaderCount != 0 {
		n += 1 + sovPd(uint64(m.LeaderCount))
	}
	return n
}

func (m *StoreHeartbeatResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ClusterID != 0 {
		n += 1 + sovPd(uint64(m.ClusterID))
	}
	return n
}

func (m *RaftGroupLeaderHeartbeatReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.StoreID != 0 {
		n += 1 + sovPd(uint64(m.StoreID))
	}
	if m.GroupID != 0 {
		n += 1 + sovPd(uint64(m.GroupID))
	}
	if m.LeaderID != 0 {
		n += 1 + sovPd(uint64(m.LeaderID))
	}
	if len(m.Peers) > 0 {
		for _, e := range m.Peers {
			l = e.Size()
			n += 1 + l + sovPd(uint64(l))
		}
	}
	return n
}

func (m *TransferLeader) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NewLeaderID != 0 {
		n += 1 + sovPd(uint64(m.NewLeaderID))
	}
	return n
}

func (m *RaftGroupLeaderHeartbeatResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TransferLeader != nil {
		l = m.TransferLeader.Size()
		n += 1 + l + sovPd(uint64(l))
	}
	return n
}

func sovPd(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozPd(x uint64) (n int) {
	return sovPd(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *StoreHeartbeatReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPd
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StoreHeartbeatReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StoreHeartbeatReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClusterID", wireType)
			}
			m.ClusterID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClusterID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoreID", wireType)
			}
			m.StoreID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StoreID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeaderCount", wireType)
			}
			m.LeaderCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LeaderCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPd(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPd
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPd
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StoreHeartbeatResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPd
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StoreHeartbeatResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StoreHeartbeatResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClusterID", wireType)
			}
			m.ClusterID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClusterID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPd(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPd
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPd
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RaftGroupLeaderHeartbeatReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPd
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RaftGroupLeaderHeartbeatReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RaftGroupLeaderHeartbeatReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoreID", wireType)
			}
			m.StoreID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StoreID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupID", wireType)
			}
			m.GroupID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GroupID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeaderID", wireType)
			}
			m.LeaderID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LeaderID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Peers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPd
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPd
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Peers = append(m.Peers, babuzapb.RaftPeerAttribute{})
			if err := m.Peers[len(m.Peers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPd(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPd
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPd
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TransferLeader) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPd
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TransferLeader: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TransferLeader: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewLeaderID", wireType)
			}
			m.NewLeaderID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NewLeaderID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPd(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPd
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPd
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RaftGroupLeaderHeartbeatResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPd
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RaftGroupLeaderHeartbeatResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RaftGroupLeaderHeartbeatResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransferLeader", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPd
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPd
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TransferLeader == nil {
				m.TransferLeader = &TransferLeader{}
			}
			if err := m.TransferLeader.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPd(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPd
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPd
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPd(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPd
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPd
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPd
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPd
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthPd
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowPd
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipPd(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthPd
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthPd = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPd   = fmt.Errorf("proto: integer overflow")
)
