// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pd.proto

package pb

import (
	context "context"
	fmt "fmt"
	babuzapb "github.com/fanaujie/babuza/ibabuza/babuzapb"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	io "io"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type StoreHeartbeatReq struct {
	ClusterID       uint64   `protobuf:"varint,1,opt,name=clusterID,proto3" json:"clusterID,omitempty"`
	StoreID         uint64   `protobuf:"varint,2,opt,name=storeID,proto3" json:"storeID,omitempty"`
	LeaderCount     uint64   `protobuf:"varint,3,opt,name=leaderCount,proto3" json:"leaderCount,omitempty"`
	RedisListenAddr string   `protobuf:"bytes,4,opt,name=redisListenAddr,proto3" json:"redisListenAddr,omitempty"`
	LeaderGroupIDs  []uint64 `protobuf:"varint,5,rep,packed,name=leaderGroupIDs,proto3" json:"leaderGroupIDs,omitempty"`
}

func (m *StoreHeartbeatReq) Reset()         { *m = StoreHeartbeatReq{} }
func (m *StoreHeartbeatReq) String() string { return proto.CompactTextString(m) }
func (*StoreHeartbeatReq) ProtoMessage()    {}
func (*StoreHeartbeatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ece4d612d87e090, []int{0}
}
func (m *StoreHeartbeatReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StoreHeartbeatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StoreHeartbeatReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StoreHeartbeatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreHeartbeatReq.Merge(m, src)
}
func (m *StoreHeartbeatReq) XXX_Size() int {
	return m.Size()
}
func (m *StoreHeartbeatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreHeartbeatReq.DiscardUnknown(m)
}

var xxx_messageInfo_StoreHeartbeatReq proto.InternalMessageInfo

type StoreHeartbeatResp struct {
	ClusterID         uint64            `protobuf:"varint,1,opt,name=clusterID,proto3" json:"clusterID,omitempty"`
	RedisRoutingTable map[uint64]string `protobuf:"bytes,2,rep,name=redisRoutingTable,proto3" json:"redisRoutingTable,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *StoreHeartbeatResp) Reset()         { *m = StoreHeartbeatResp{} }
func (m *StoreHeartbeatResp) String() string { return proto.CompactTextString(m) }
func (*StoreHeartbeatResp) ProtoMessage()    {}
func (*StoreHeartbeatResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ece4d612d87e090, []int{1}
}
func (m *StoreHeartbeatResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StoreHeartbeatResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StoreHeartbeatResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StoreHeartbeatResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreHeartbeatResp.Merge(m, src)
}
func (m *StoreHeartbeatResp) XXX_Size() int {
	return m.Size()
}
func (m *StoreHeartbeatResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreHeartbeatResp.DiscardUnknown(m)
}

var xxx_messageInfo_StoreHeartbeatResp proto.InternalMessageInfo

type RaftGroupLeaderHeartbeatReq struct {
	StoreID  uint64                       `protobuf:"varint,1,opt,name=storeID,proto3" json:"storeID,omitempty"`
	GroupID  uint64                       `protobuf:"varint,2,opt,name=groupID,proto3" json:"groupID,omitempty"`
	LeaderID uint64                       `protobuf:"varint,3,opt,name=leaderID,proto3" json:"leaderID,omitempty"`
	Peers    []babuzapb.RaftPeerAttribute `protobuf:"bytes,4,rep,name=peers,proto3" json:"peers"`
}

func (m *RaftGroupLeaderHeartbeatReq) Reset()         { *m = RaftGroupLeaderHeartbeatReq{} }
func (m *RaftGroupLeaderHeartbeatReq) String() string { return proto.CompactTextString(m) }
func (*RaftGroupLeaderHeartbeatReq) ProtoMessage()    {}
func (*RaftGroupLeaderHeartbeatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ece4d612d87e090, []int{2}
}
func (m *RaftGroupLeaderHeartbeatReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RaftGroupLeaderHeartbeatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RaftGroupLeaderHeartbeatReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RaftGroupLeaderHeartbeatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RaftGroupLeaderHeartbeatReq.Merge(m, src)
}
func (m *RaftGroupLeaderHeartbeatReq) XXX_Size() int {
	return m.Size()
}
func (m *RaftGroupLeaderHeartbeatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RaftGroupLeaderHeartbeatReq.DiscardUnknown(m)
}

var xxx_messageInfo_RaftGroupLeaderHeartbeatReq proto.InternalMessageInfo

type TransferLeader struct {
	NewLeaderID uint64 `protobuf:"varint,1,opt,name=newLeaderID,proto3" json:"newLeaderID,omitempty"`
}

func (m *TransferLeader) Reset()         { *m = TransferLeader{} }
func (m *TransferLeader) String() string { return proto.CompactTextString(m) }
func (*TransferLeader) ProtoMessage()    {}
func (*TransferLeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ece4d612d87e090, []int{3}
}
func (m *TransferLeader) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TransferLeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TransferLeader.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TransferLeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferLeader.Merge(m, src)
}
func (m *TransferLeader) XXX_Size() int {
	return m.Size()
}
func (m *TransferLeader) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferLeader.DiscardUnknown(m)
}

var xxx_messageInfo_TransferLeader proto.InternalMessageInfo

type RaftGroupLeaderHeartbeatResp struct {
	TransferLeader *TransferLeader `protobuf:"bytes,1,opt,name=transferLeader,proto3" json:"transferLeader,omitempty"`
}

func (m *RaftGroupLeaderHeartbeatResp) Reset()         { *m = RaftGroupLeaderHeartbeatResp{} }
func (m *RaftGroupLeaderHeartbeatResp) String() string { return proto.CompactTextString(m) }
func (*RaftGroupLeaderHeartbeatResp) ProtoMessage()    {}
func (*RaftGroupLeaderHeartbeatResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ece4d612d87e090, []int{4}
}
func (m *RaftGroupLeaderHeartbeatResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RaftGroupLeaderHeartbeatResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RaftGroupLeaderHeartbeatResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RaftGroupLeaderHeartbeatResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RaftGroupLeaderHeartbeatResp.Merge(m, src)
}
func (m *RaftGroupLeaderHeartbeatResp) XXX_Size() int {
	return m.Size()
}
func (m *RaftGroupLeaderHeartbeatResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RaftGroupLeaderHeartbeatResp.DiscardUnknown(m)
}

var xxx_messageInfo_RaftGroupLeaderHeartbeatResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*StoreHeartbeatReq)(nil), "pdpb.StoreHeartbeatReq")
	proto.RegisterType((*StoreHeartbeatResp)(nil), "pdpb.StoreHeartbeatResp")
	proto.RegisterMapType((map[uint64]string)(nil), "pdpb.StoreHeartbeatResp.RedisRoutingTableEntry")
	proto.RegisterType((*RaftGroupLeaderHeartbeatReq)(nil), "pdpb.RaftGroupLeaderHeartbeatReq")
	proto.RegisterType((*TransferLeader)(nil), "pdpb.TransferLeader")
	proto.RegisterType((*RaftGroupLeaderHeartbeatResp)(nil), "pdpb.RaftGroupLeaderHeartbeatResp")
}

func init() { proto.RegisterFile("pd.proto", fileDescriptor_3ece4d612d87e090) }

var fileDescriptor_3ece4d612d87e090 = []byte{
	// 538 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0xbd, 0x8d, 0x4b, 0x9b, 0x09, 0x0a, 0x74, 0x15, 0x81, 0x31, 0x95, 0x09, 0x3e, 0xa0,
	0x5c, 0xb0, 0xa5, 0x20, 0xa4, 0x0a, 0x71, 0x69, 0x71, 0x05, 0x91, 0x72, 0xa8, 0xdc, 0x9e, 0x2a,
	0x38, 0xac, 0xe3, 0x89, 0x31, 0x4d, 0x6d, 0x77, 0xbd, 0x2e, 0x94, 0xa7, 0xe0, 0x21, 0x78, 0x07,
	0x8e, 0x5c, 0x73, 0xcc, 0x0d, 0x4e, 0x88, 0x26, 0x2f, 0x82, 0xbc, 0x9b, 0x40, 0x92, 0x36, 0xf4,
	0xe6, 0xf9, 0xef, 0x7c, 0xff, 0xc6, 0xb0, 0x99, 0x85, 0x4e, 0xc6, 0x53, 0x91, 0x52, 0x3d, 0x0b,
	0xb3, 0xc0, 0x6c, 0x44, 0x69, 0x94, 0x4a, 0xc1, 0x2d, 0xbf, 0xd4, 0x9b, 0x79, 0x3b, 0x60, 0x41,
	0xf1, 0x99, 0x29, 0xcb, 0xfe, 0x4e, 0x60, 0xeb, 0x50, 0xa4, 0x1c, 0xdf, 0x20, 0xe3, 0x22, 0x40,
	0x26, 0x7c, 0x3c, 0xa3, 0xdb, 0x50, 0xed, 0x0d, 0x8a, 0x5c, 0x20, 0xef, 0x78, 0x06, 0x69, 0x92,
	0x96, 0xee, 0xff, 0x13, 0xa8, 0x01, 0x1b, 0x79, 0x19, 0xd2, 0xf1, 0x8c, 0x35, 0xf9, 0x36, 0x33,
	0x69, 0x13, 0x6a, 0x03, 0x64, 0x21, 0xf2, 0x57, 0x69, 0x91, 0x08, 0xa3, 0x22, 0x5f, 0xe7, 0x25,
	0xda, 0x82, 0x3b, 0x1c, 0xc3, 0x38, 0xef, 0xc6, 0xb9, 0xc0, 0x64, 0x37, 0x0c, 0xb9, 0xa1, 0x37,
	0x49, 0xab, 0xea, 0x2f, 0xcb, 0xf4, 0x09, 0xd4, 0x55, 0xe0, 0x6b, 0x9e, 0x16, 0x59, 0xc7, 0xcb,
	0x8d, 0xf5, 0x66, 0xa5, 0xa5, 0xfb, 0x4b, 0xaa, 0xfd, 0x83, 0x00, 0x5d, 0x9e, 0x20, 0xcf, 0x6e,
	0x18, 0xe1, 0x1d, 0x6c, 0xc9, 0x7a, 0x7e, 0x5a, 0x88, 0x38, 0x89, 0x8e, 0x58, 0x30, 0x40, 0x63,
	0xad, 0x59, 0x69, 0xd5, 0xda, 0xae, 0x53, 0x2e, 0xcf, 0xb9, 0x9a, 0xd2, 0xf1, 0x97, 0x23, 0xf6,
	0x13, 0xc1, 0x2f, 0xfc, 0xab, 0x99, 0x4c, 0x0f, 0xee, 0x5d, 0xef, 0x4c, 0xef, 0x42, 0xe5, 0x04,
	0x2f, 0xa6, 0x0d, 0x95, 0x9f, 0xb4, 0x01, 0xeb, 0xe7, 0x6c, 0x50, 0xa0, 0xdc, 0x65, 0xd5, 0x57,
	0xc6, 0x8b, 0xb5, 0x1d, 0x62, 0x7f, 0x25, 0xf0, 0xd0, 0x67, 0x7d, 0x21, 0x47, 0xed, 0xca, 0xa9,
	0x17, 0x28, 0xcd, 0x71, 0x20, 0x8b, 0x1c, 0x0c, 0xd8, 0x88, 0xd4, 0x7e, 0x66, 0x84, 0xa6, 0x26,
	0x35, 0x61, 0x53, 0xed, 0xaf, 0xe3, 0x4d, 0xf1, 0xfc, 0xb5, 0xe9, 0x73, 0x58, 0xcf, 0x10, 0x79,
	0x6e, 0xe8, 0x72, 0x11, 0x0f, 0x9c, 0xe9, 0xa5, 0x94, 0x3d, 0x1c, 0x20, 0xf2, 0x5d, 0x21, 0x78,
	0x1c, 0x14, 0x02, 0xf7, 0xf4, 0xe1, 0xaf, 0x47, 0x9a, 0xaf, 0xbc, 0xed, 0x36, 0xd4, 0x8f, 0x38,
	0x4b, 0xf2, 0x3e, 0x72, 0xd5, 0x64, 0x79, 0x06, 0x09, 0x7e, 0xec, 0xce, 0xea, 0xa8, 0xe6, 0xe6,
	0x25, 0xfb, 0x2d, 0x6c, 0xaf, 0x9e, 0x2c, 0xcf, 0xe8, 0x4b, 0xa8, 0x8b, 0x85, 0x9c, 0x32, 0x49,
	0xad, 0xdd, 0x50, 0x70, 0x16, 0xeb, 0xf9, 0x4b, 0xbe, 0xed, 0x6f, 0x04, 0xaa, 0x07, 0xde, 0x21,
	0xf2, 0xf3, 0xb8, 0x87, 0x74, 0x1f, 0xea, 0x8b, 0x30, 0xe9, 0xfd, 0xeb, 0x11, 0x9f, 0x99, 0xc6,
	0x2a, 0xf6, 0xb6, 0x46, 0x7b, 0x60, 0xac, 0x6a, 0x99, 0x3e, 0x56, 0x71, 0xff, 0x81, 0x65, 0xda,
	0x37, 0xb9, 0x94, 0x45, 0xf6, 0x8e, 0x87, 0x97, 0x96, 0x36, 0xba, 0xb4, 0xb4, 0xe1, 0xd8, 0x22,
	0xa3, 0xb1, 0x45, 0x7e, 0x8f, 0x2d, 0xf2, 0x65, 0x62, 0x69, 0xa3, 0x89, 0xa5, 0xfd, 0x9c, 0x58,
	0xda, 0xf1, 0x4e, 0x14, 0x8b, 0xf7, 0x45, 0xe0, 0xf4, 0xd2, 0x53, 0xb7, 0xcf, 0x12, 0x56, 0x7c,
	0x88, 0xd1, 0x55, 0xa0, 0x5c, 0xfc, 0xc4, 0x4e, 0xb3, 0x01, 0xe6, 0xae, 0xbc, 0xc8, 0xa7, 0xd3,
	0x73, 0x77, 0xb3, 0x93, 0xc8, 0xcd, 0x82, 0xe0, 0x96, 0xfc, 0xe3, 0x9f, 0xfd, 0x09, 0x00, 0x00,
	0xff, 0xff, 0x52, 0xad, 0xeb, 0x8c, 0x27, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PDServiceClient is the client API for PDService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PDServiceClient interface {
	StoreHeartbeat(ctx context.Context, in *StoreHeartbeatReq, opts ...grpc.CallOption) (*StoreHeartbeatResp, error)
	RaftGroupLeaderHeartbeat(ctx context.Context, in *RaftGroupLeaderHeartbeatReq, opts ...grpc.CallOption) (*RaftGroupLeaderHeartbeatResp, error)
}

type pDServiceClient struct {
	cc *grpc.ClientConn
}

func NewPDServiceClient(cc *grpc.ClientConn) PDServiceClient {
	return &pDServiceClient{cc}
}

func (c *pDServiceClient) StoreHeartbeat(ctx context.Context, in *StoreHeartbeatReq, opts ...grpc.CallOption) (*StoreHeartbeatResp, error) {
	out := new(StoreHeartbeatResp)
	err := c.cc.Invoke(ctx, "/pdpb.PDService/StoreHeartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pDServiceClient) RaftGroupLeaderHeartbeat(ctx context.Context, in *RaftGroupLeaderHeartbeatReq, opts ...grpc.CallOption) (*RaftGroupLeaderHeartbeatResp, error) {
	out := new(RaftGroupLeaderHeartbeatResp)
	err := c.cc.Invoke(ctx, "/pdpb.PDService/RaftGroupLeaderHeartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PDServiceServer is the server API for PDService service.
type PDServiceServer interface {
	StoreHeartbeat(context.Context, *StoreHeartbeatReq) (*StoreHeartbeatResp, error)
	RaftGroupLeaderHeartbeat(context.Context, *RaftGroupLeaderHeartbeatReq) (*RaftGroupLeaderHeartbeatResp, error)
}

func RegisterPDServiceServer(s *grpc.Server, srv PDServiceServer) {
	s.RegisterService(&_PDService_serviceDesc, srv)
}

func _PDService_StoreHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreHeartbeatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PDServiceServer).StoreHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pdpb.PDService/StoreHeartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PDServiceServer).StoreHeartbeat(ctx, req.(*StoreHeartbeatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PDService_RaftGroupLeaderHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RaftGroupLeaderHeartbeatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PDServiceServer).RaftGroupLeaderHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pdpb.PDService/RaftGroupLeaderHeartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PDServiceServer).RaftGroupLeaderHeartbeat(ctx, req.(*RaftGroupLeaderHeartbeatReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _PDService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pdpb.PDService",
	HandlerType: (*PDServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreHeartbeat",
			Handler:    _PDService_StoreHeartbeat_Handler,
		},
		{
			MethodName: "RaftGroupLeaderHeartbeat",
			Handler:    _PDService_RaftGroupLeaderHeartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pd.proto",
}

func (m *StoreHeartbeatReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StoreHeartbeatReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ClusterID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintPd(dAtA, i, uint64(m.ClusterID))
	}
	if m.StoreID != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintPd(dAtA, i, uint64(m.StoreID))
	}
	if m.LeaderCount != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintPd(dAtA, i, uint64(m.LeaderCount))
	}
	if len(m.RedisListenAddr) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintPd(dAtA, i, uint64(len(m.RedisListenAddr)))
		i += copy(dAtA[i:], m.RedisListenAddr)
	}
	if len(m.LeaderGroupIDs) > 0 {
		dAtA2 := make([]byte, len(m.LeaderGroupIDs)*10)
		var j1 int
		for _, num := range m.LeaderGroupIDs {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		dAtA[i] = 0x2a
		i++
		i = encodeVarintPd(dAtA, i, uint64(j1))
		i += copy(dAtA[i:], dAtA2[:j1])
	}
	return i, nil
}

func (m *StoreHeartbeatResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StoreHeartbeatResp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ClusterID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintPd(dAtA, i, uint64(m.ClusterID))
	}
	if len(m.RedisRoutingTable) > 0 {
		for k, _ := range m.RedisRoutingTable {
			dAtA[i] = 0x12
			i++
			v := m.RedisRoutingTable[k]
			mapSize := 1 + sovPd(uint64(k)) + 1 + len(v) + sovPd(uint64(len(v)))
			i = encodeVarintPd(dAtA, i, uint64(mapSize))
			dAtA[i] = 0x8
			i++
			i = encodeVarintPd(dAtA, i, uint64(k))
			dAtA[i] = 0x12
			i++
			i = encodeVarintPd(dAtA, i, uint64(len(v)))
			i += copy(dAtA[i:], v)
		}
	}
	return i, nil
}

func (m *RaftGroupLeaderHeartbeatReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RaftGroupLeaderHeartbeatReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.StoreID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintPd(dAtA, i, uint64(m.StoreID))
	}
	if m.GroupID != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintPd(dAtA, i, uint64(m.GroupID))
	}
	if m.LeaderID != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintPd(dAtA, i, uint64(m.LeaderID))
	}
	if len(m.Peers) > 0 {
		for _, msg := range m.Peers {
			dAtA[i] = 0x22
			i++
			i = encodeVarintPd(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *TransferLeader) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TransferLeader) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.NewLeaderID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintPd(dAtA, i, uint64(m.NewLeaderID))
	}
	return i, nil
}

func (m *RaftGroupLeaderHeartbeatResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RaftGroupLeaderHeartbeatResp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.TransferLeader != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintPd(dAtA, i, uint64(m.TransferLeader.Size()))
		n3, err := m.TransferLeader.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	return i, nil
}

func encodeVarintPd(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *StoreHeartbeatReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ClusterID != 0 {
		n += 1 + sovPd(uint64(m.ClusterID))
	}
	if m.StoreID != 0 {
		n += 1 + sovPd(uint64(m.StoreID))
	}
	if m.LeaderCount != 0 {
		n += 1 + sovPd(uint64(m.LeaderCount))
	}
	l = len(m.RedisListenAddr)
	if l > 0 {
		n += 1 + l + sovPd(uint64(l))
	}
	if len(m.LeaderGroupIDs) > 0 {
		l = 0
		for _, e := range m.LeaderGroupIDs {
			l += sovPd(uint64(e))
		}
		n += 1 + sovPd(uint64(l)) + l
	}
	return n
}

func (m *StoreHeartbeatResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ClusterID != 0 {
		n += 1 + sovPd(uint64(m.ClusterID))
	}
	if len(m.RedisRoutingTable) > 0 {
		for k, v := range m.RedisRoutingTable {
			_ = k
			_ = v
			mapEntrySize := 1 + sovPd(uint64(k)) + 1 + len(v) + sovPd(uint64(len(v)))
			n += mapEntrySize + 1 + sovPd(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *RaftGroupLeaderHeartbeatReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.StoreID != 0 {
		n += 1 + sovPd(uint64(m.StoreID))
	}
	if m.GroupID != 0 {
		n += 1 + sovPd(uint64(m.GroupID))
	}
	if m.LeaderID != 0 {
		n += 1 + sovPd(uint64(m.LeaderID))
	}
	if len(m.Peers) > 0 {
		for _, e := range m.Peers {
			l = e.Size()
			n += 1 + l + sovPd(uint64(l))
		}
	}
	return n
}

func (m *TransferLeader) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NewLeaderID != 0 {
		n += 1 + sovPd(uint64(m.NewLeaderID))
	}
	return n
}

func (m *RaftGroupLeaderHeartbeatResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TransferLeader != nil {
		l = m.TransferLeader.Size()
		n += 1 + l + sovPd(uint64(l))
	}
	return n
}

func sovPd(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozPd(x uint64) (n int) {
	return sovPd(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *StoreHeartbeatReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPd
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StoreHeartbeatReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StoreHeartbeatReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClusterID", wireType)
			}
			m.ClusterID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClusterID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoreID", wireType)
			}
			m.StoreID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StoreID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeaderCount", wireType)
			}
			m.LeaderCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LeaderCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RedisListenAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPd
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPd
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RedisListenAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowPd
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.LeaderGroupIDs = append(m.LeaderGroupIDs, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowPd
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthPd
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthPd
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.LeaderGroupIDs) == 0 {
					m.LeaderGroupIDs = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowPd
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.LeaderGroupIDs = append(m.LeaderGroupIDs, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field LeaderGroupIDs", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPd(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPd
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPd
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StoreHeartbeatResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPd
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StoreHeartbeatResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StoreHeartbeatResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClusterID", wireType)
			}
			m.ClusterID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClusterID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RedisRoutingTable", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPd
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPd
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RedisRoutingTable == nil {
				m.RedisRoutingTable = make(map[uint64]string)
			}
			var mapkey uint64
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowPd
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowPd
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowPd
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthPd
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthPd
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipPd(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthPd
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.RedisRoutingTable[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPd(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPd
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPd
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RaftGroupLeaderHeartbeatReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPd
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RaftGroupLeaderHeartbeatReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RaftGroupLeaderHeartbeatReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoreID", wireType)
			}
			m.StoreID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StoreID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupID", wireType)
			}
			m.GroupID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GroupID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeaderID", wireType)
			}
			m.LeaderID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LeaderID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Peers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPd
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPd
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Peers = append(m.Peers, babuzapb.RaftPeerAttribute{})
			if err := m.Peers[len(m.Peers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPd(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPd
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPd
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TransferLeader) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPd
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TransferLeader: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TransferLeader: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewLeaderID", wireType)
			}
			m.NewLeaderID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NewLeaderID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPd(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPd
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPd
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RaftGroupLeaderHeartbeatResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPd
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RaftGroupLeaderHeartbeatResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RaftGroupLeaderHeartbeatResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransferLeader", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPd
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPd
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TransferLeader == nil {
				m.TransferLeader = &TransferLeader{}
			}
			if err := m.TransferLeader.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPd(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPd
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPd
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPd(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPd
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPd
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPd
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPd
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthPd
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowPd
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipPd(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthPd
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthPd = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPd   = fmt.Errorf("proto: integer overflow")
)
