// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: redis.proto

package pb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type RedisDataType int32

const (
	RedisDataType_None   RedisDataType = 0
	RedisDataType_String RedisDataType = 1
)

var RedisDataType_name = map[int32]string{
	0: "None",
	1: "String",
}

var RedisDataType_value = map[string]int32{
	"None":   0,
	"String": 1,
}

func (x RedisDataType) String() string {
	return proto.EnumName(RedisDataType_name, int32(x))
}

func (RedisDataType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d954120a2319ff8f, []int{0}
}

type RedisCommand struct {
	Type                 RedisDataType `protobuf:"varint,1,opt,name=type,proto3,enum=redispb.RedisDataType" json:"type,omitempty"`
	Command              string        `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	ArgsLength           int64         `protobuf:"varint,3,opt,name=argsLength,proto3" json:"argsLength,omitempty"`
	Args                 [][]byte      `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RedisCommand) Reset()         { *m = RedisCommand{} }
func (m *RedisCommand) String() string { return proto.CompactTextString(m) }
func (*RedisCommand) ProtoMessage()    {}
func (*RedisCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_d954120a2319ff8f, []int{0}
}
func (m *RedisCommand) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RedisCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RedisCommand.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RedisCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisCommand.Merge(m, src)
}
func (m *RedisCommand) XXX_Size() int {
	return m.Size()
}
func (m *RedisCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisCommand.DiscardUnknown(m)
}

var xxx_messageInfo_RedisCommand proto.InternalMessageInfo

func (m *RedisCommand) GetType() RedisDataType {
	if m != nil {
		return m.Type
	}
	return RedisDataType_None
}

func (m *RedisCommand) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *RedisCommand) GetArgsLength() int64 {
	if m != nil {
		return m.ArgsLength
	}
	return 0
}

func (m *RedisCommand) GetArgs() [][]byte {
	if m != nil {
		return m.Args
	}
	return nil
}

func init() {
	proto.RegisterEnum("redispb.RedisDataType", RedisDataType_name, RedisDataType_value)
	proto.RegisterType((*RedisCommand)(nil), "redispb.RedisCommand")
}

func init() { proto.RegisterFile("redis.proto", fileDescriptor_d954120a2319ff8f) }

var fileDescriptor_d954120a2319ff8f = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x8d, 0x5d, 0x5a, 0x1d, 0xab, 0x94, 0x1c, 0x24, 0xa7, 0x65, 0x11, 0x84, 0xa5, 0xe0,
	0x06, 0xf4, 0xe2, 0x59, 0xc5, 0x93, 0x78, 0x88, 0x9e, 0xbc, 0x4d, 0xb6, 0x63, 0xba, 0xda, 0x4d,
	0x42, 0x36, 0x0b, 0xd6, 0x27, 0xf0, 0xd1, 0x3c, 0xfa, 0x08, 0xb2, 0x4f, 0x22, 0x8d, 0x0a, 0x7a,
	0xfb, 0xbf, 0xe1, 0x1b, 0x86, 0xf9, 0x61, 0x2f, 0xd0, 0xa2, 0xe9, 0x2a, 0x1f, 0x5c, 0x74, 0x7c,
	0x92, 0xc0, 0xeb, 0xa3, 0x37, 0x06, 0x53, 0xb5, 0xc9, 0x97, 0xae, 0x6d, 0xd1, 0x2e, 0xf8, 0x1c,
	0xb2, 0xb8, 0xf6, 0x24, 0x58, 0xc1, 0xca, 0x83, 0xd3, 0xc3, 0xea, 0x47, 0xac, 0x92, 0x74, 0x85,
	0x11, 0xef, 0xd7, 0x9e, 0x54, 0x72, 0xb8, 0x80, 0x49, 0xfd, 0xbd, 0x26, 0xb6, 0x0b, 0x56, 0xee,
	0xaa, 0x5f, 0xe4, 0x39, 0x00, 0x06, 0xd3, 0xdd, 0x90, 0x35, 0x71, 0x29, 0x46, 0x05, 0x2b, 0x47,
	0xea, 0xcf, 0x84, 0x73, 0xc8, 0x36, 0x24, 0xb2, 0x62, 0x54, 0x4e, 0x55, 0xca, 0xf3, 0x63, 0xd8,
	0xff, 0x77, 0x84, 0xef, 0x40, 0x76, 0xeb, 0x2c, 0xcd, 0xb6, 0x38, 0xc0, 0xf8, 0x2e, 0x86, 0xc6,
	0x9a, 0x19, 0xbb, 0xb8, 0x7e, 0x1f, 0x72, 0xf6, 0x31, 0xe4, 0xec, 0x73, 0xc8, 0xd9, 0xc3, 0xb9,
	0x69, 0xe2, 0xb2, 0xd7, 0x55, 0xed, 0x5a, 0xf9, 0x88, 0x16, 0xfb, 0xa7, 0x86, 0xa4, 0x46, 0xdd,
	0xbf, 0xa2, 0xa4, 0x17, 0x6c, 0xfd, 0x8a, 0x3a, 0x99, 0x7e, 0x38, 0xa9, 0x57, 0x7d, 0x17, 0x29,
	0x48, 0xff, 0x6c, 0xa4, 0xd7, 0x7a, 0x9c, 0x9a, 0x38, 0xfb, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xaa,
	0x93, 0x4b, 0x9f, 0x18, 0x01, 0x00, 0x00,
}

func (m *RedisCommand) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RedisCommand) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Type != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintRedis(dAtA, i, uint64(m.Type))
	}
	if len(m.Command) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintRedis(dAtA, i, uint64(len(m.Command)))
		i += copy(dAtA[i:], m.Command)
	}
	if m.ArgsLength != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintRedis(dAtA, i, uint64(m.ArgsLength))
	}
	if len(m.Args) > 0 {
		for _, b := range m.Args {
			dAtA[i] = 0x22
			i++
			i = encodeVarintRedis(dAtA, i, uint64(len(b)))
			i += copy(dAtA[i:], b)
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintRedis(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *RedisCommand) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Type != 0 {
		n += 1 + sovRedis(uint64(m.Type))
	}
	l = len(m.Command)
	if l > 0 {
		n += 1 + l + sovRedis(uint64(l))
	}
	if m.ArgsLength != 0 {
		n += 1 + sovRedis(uint64(m.ArgsLength))
	}
	if len(m.Args) > 0 {
		for _, b := range m.Args {
			l = len(b)
			n += 1 + l + sovRedis(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovRedis(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozRedis(x uint64) (n int) {
	return sovRedis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RedisCommand) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRedis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RedisCommand: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RedisCommand: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRedis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= RedisDataType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Command", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRedis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRedis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRedis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Command = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ArgsLength", wireType)
			}
			m.ArgsLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRedis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ArgsLength |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Args", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRedis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthRedis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthRedis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Args = append(m.Args, make([]byte, postIndex-iNdEx))
			copy(m.Args[len(m.Args)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRedis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRedis
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthRedis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRedis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRedis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRedis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRedis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRedis
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthRedis
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowRedis
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipRedis(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthRedis
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthRedis = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRedis   = fmt.Errorf("proto: integer overflow")
)
